### ISSUE TITLE
[Enhancement] Support Yeelight Wireless Switch S1 - YLAI003

### ISSUE THREAD

**Issue by andrewjswan** [custom-components/ble_monitor#268] opened 2021-02-10 08:31 UTC
**Yeelight Wireless Switch S1** - **YLAI003** - https://aliexpress.ru/item/1005001552119268.html
The button has three actions, press, double press, long press.
There is also a battery charge value.
When i add it to MiHome, a bindkey was generated.
I will try to dump the unknown packages one day.

**Comment by andrewjswan** [comment] 2021-02-10 18:28
20:08 - 20:14 ... ~10 press +- ... ~10 double press ... ~10 long press. :)
20:15 connect to Alarm clock, change format from 24H to 12H and back... set alarm to 20:17 and alarm fired ...
20:18 +- connect again and delete alarm
20:19 3 press to Yeelight Wireless Switch S1, 3 double press and 3 long press
20:20 Some turn Xiaomi Cubic right right left left ... right right left left ... right right left left ...

Yeelight Wireless Switch S1 - 28:D1:27:39:A7:BF
Alarm clock - 58:2D:34:51:C6:29
Xiaomi Cubic I dont know ... :
[home-assistant.log.zip](https://github.com/custom-components/ble_monitor/files/5960558/home-assistant.log.zip)
(

**Comment by andrewjswan** [comment] 2021-02-10 18:31
@Ernst79 Bindkey - 1d6fe5b915bc7586b0f652e843ea8a8d Tell me when you pick it up, I'll delete ... :)

**Comment by Ernst79** [comment] 2021-02-10 19:25
Got it, safe to delete the key

**Comment by Ernst79** [comment] 2021-02-10 21:43
There is useful in the message. I will collect some decrypted messages coming days below (not finished). Will update this post during coming days with more info. 

**10 press +-**
20:09:54 `011003000000` --> type `01 00` length `03` command `000000`
**10 double press**
20:12:01 `011003000001` --> type `01 00` length `03` command `000001`
**10 long press**
20:13:22 `011003000002` --> type `01 00` length `03` command `000002`

**Comment by andrewjswan** [comment] 2021-02-10 22:04
Great, now it should be implemented in the structure of HA, and I think everything will work, though I do not know how the buttons work in HA, and what are the standard statuses there.

**Comment by Ernst79** [comment] 2021-02-10 22:10
Cube has MAC E2:53:30:E6:D3:54, but only two message are present. They don't contain useful data. 

About the structure of HA, I have to check what makes most sense. 

We can always make a binary sensor, but there is no `off` message. But I will first check other possibilities.

**Comment by andrewjswan** [comment] 2021-02-11 08:32
> Cube has MAC E2:53:30:E6:D3:54, but only two message are present. They don't contain useful data.
> 
> About the structure of HA, I have to check what makes most sense.
> 
> We can always make a binary sensor, but there is no `off` message. But I will first check other possibilities.

Binary sensor is not a good idea, HA has button support, but I think it is a simple sensor with different values, and auto reset to default state. Like - https://github.com/AlexxIT/XiaomiGateway3/blob/master/custom_components/xiaomi_gateway3/sensor.py#L228-L238

For this button we need 3 states - 'single', 'double', 'long' ... and 'off' :) or similar :)

> Cube has MAC E2:53:30:E6:D3:54, but only two message are present. They don't contain useful data.

The kid has the cube, and he doesn't want to give it much to experiment with, but I found a breakdown of his protocol on the Internet. And I can try again a little later to collect information on it. Although without a gateway it may not transmit the necessary information, and because it is tied to the child's account, and he does not have a gateway, it may be in standby mode.

**Comment by Ernst79** [comment] 2021-02-11 10:41
OK, I can create a sensor with 3 states, no problem. 

Note to myself: This button sensor should not do averaging of data, but should respond immediately on each message, similar as the binary sensors.

**Comment by andrewjswan** [comment] 2021-02-11 10:57
> This button sensor should not do averaging of data, but should respond immediately on each message, similar as the binary sensors.

Yes, it is, but after some time should return to the unpressed state, after how long I do not know, but I think half a second should be enough to automate.

**Comment by andrewjswan** [comment] 2021-02-12 11:11
> OK, I can create a sensor with 3 states, no problem.

Thanks! Wait for Test :)

**Comment by Ernst79** [comment] 2021-02-12 11:26
Almost finished, I had some troubles with the data-collecting of measurement sensors, which we do not want for a button.

![image](https://user-images.githubusercontent.com/24375847/107762500-64618280-6d2d-11eb-8fa8-f75ae786094c.png)

(I misuse a moisture sensor for mimic your sensor)

**Comment by andrewjswan** [comment] 2021-02-12 11:44
> Almost finished,

Its one sensor with states like single, double, long or hold?

**Comment by Ernst79** [comment] 2021-02-12 11:50
Yep, I now have "single press", "double press", "long press" and (after 1 second) "no press" 

I let you do the testing for the time, what works best

**Comment by Ernst79** [comment] 2021-02-12 21:31
Please give it a try. You will need to copy `__init__.py`, `const.py` and `sensor.py` from this [branch](https://github.com/custom-components/ble_monitor/tree/YLAI003). 

I added a attribute as well, that shows the "last pressed button". 

You can play with the time at line 717 in `sensor.py`, by changing the `1`

`async_call_later(self.hass, 1, self.reset_state)`

Besides checking that it works, could you tell me if the battery state is added after a while? Will take a while, so wait at least an hour, battery state messages are not send that often. 

Please also check the log, that there isn't any error (ble monitor related).

**Comment by andrewjswan** [comment] 2021-02-13 09:03
> Besides checking that it works, could you tell me if the battery state is added after a while?

2 minutes after start:
![image](https://user-images.githubusercontent.com/3609660/107846279-20cd4e00-6deb-11eb-8b39-8ea670d61be3.png)

**Comment by andrewjswan** [comment] 2021-02-13 09:13
Works without problems, I do not need to reduce the time is fast enough as it is. Automation has not checked yet, a little later. Thanks!

**Comment by Ernst79** [comment] 2021-02-13 10:35
OK, great, will make a new beta release asap. Automations are independent of ble monitor. Just create something that acts on a state change should work.

**Comment by andrewjswan** [comment] 2021-02-13 10:44
But when the signal is weak ~ -94 RSSI, it does not always work. :( Although the data on the battery charge always comes out perfectly. There are no errors in the log.

**Comment by andrewjswan** [comment] 2021-02-13 10:44
> Automations are independent of ble monitor. Just create something that acts on a state change should work.

Work perfect ...

**Comment by Ernst79** [comment] 2021-02-13 11:41
1.0.4-beta has been released. Only changed the manufacturer to Yeelight in stead of Xiaomi.

**Comment by Ernst79** [comment] 2021-02-16 08:47
1.0.4. has been released. Closing this issue.

**Closed by Ernst79** 2021-02-16 08:47 UTC

**Comment by RaspiGame** [comment] 2021-02-25 00:54
Hi all, first of all thanks for the integration ;)
I've been testing this button with with automations and I figure out that the attribute "last button press" isn't resetting after a second to 'no press' as state's button do.
Could some one verify this behavior to ensure that isn't my issue?

thanks for the gread job

**Comment by Ernst79** [comment] 2021-02-25 06:40
This is “by design”. The state of the button sensor goes back to “no press” after one second. But I thought that it might be interesting for a user to know which button was pressed last. So, the attribute “last button press” remembers the last button you have pressed, it updates on each press but isn’t set back to no press (as this would make it impossible to see what button you pressed the last time). This attribute can be used for other types of automations

**Comment by RaspiGame** [comment] 2021-02-25 09:34
Ok, it's seems logical for that attribute. The question is that I'm unable to make automation with the trigger using button's state, at least by UI. Just appear the battery's level type. I'm doing something wrong?

**Comment by Ernst79** [comment] 2021-02-25 09:54
the attribute field is optional, you can leave it empty if you want to use the state of the button itself. I don't have this device myself, but it should look something like this. You might need quote marks around "no press", not sure. But leave the attribute field empty. 

![image](https://user-images.githubusercontent.com/24375847/109135796-c1126380-7757-11eb-8aa5-b0c89174ff90.png)

**Comment by RaspiGame** [comment] 2021-02-25 22:28
Your're right, work perfectly 👌
Thanks for your support!
