### ISSUE TITLE
[Enhancement] Support new RTCGQ02LM Xiaomi Mi Motion Sensor 2

### ISSUE THREAD

**Issue by paracetamol32** [custom-components/ble_monitor#253] opened 2021-01-31 15:08 UTC
is there a possibility to support  the new RTCGQ02LM Xiaomi Mi Motion Sensor 2 ?

**Comment by Ernst79** [comment] 2021-01-31 15:26
Sure, but we need some information. The faq gives an explanation on how to collect the data from the sensor to be implemented.

https://github.com/custom-components/ble_monitor/blob/master/faq.md#my-sensor-from-the-xiaomi-ecosystem-is-not-in-the-list-of-supported-ones-how-to-request-implementation

**Comment by paracetamol32** [comment] 2021-01-31 15:41
Ok 👍 i do this and give you feed back

**Comment by andrewjswan** [comment] 2021-02-03 11:35
> my dongle is a BT 4.0 and this new sensor is a BT 5.0 :(

If the dongle supports BLE then no matter what version 4.0 or 5.0 should work.

**Comment by Ernst79** [comment] 2021-02-16 08:48
Any progress in getting the data? If you need help, let me know.

**Comment by andriensis** [comment] 2021-02-17 15:07
@Ernst79 
I will try and get the sensor data. 
Should the device be paired with any Xiaomi hub or do they usually broadcast data without being paired?

**Comment by Ernst79** [comment] 2021-02-17 15:24
Normally, it should be added to MiHome, to send usable data.

**Comment by andriensis** [comment] 2021-02-17 15:25
Okay, thanks. Should I also collect some logs in pairing mode?

**Comment by Ernst79** [comment] 2021-02-17 15:46
No, we only need the messages when not in pairing mode.

**Comment by andriensis** [comment] 2021-02-17 16:05
@Ernst79 

Here you go! 
Let me know if you need specific logs (e.g. when the sensor detects movement)

2021-02-17 16:56:03 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -69, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a0e0fc4e044ef54bb
2021-02-17 16:56:03 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -69, MAC: 54EF44E0C40F, ADV: 043e2b020103000fc4e044ef541f0201061b1695fe58598d0a170fc4e044ef547cc27a5c03a1000000790df258bb
2021-02-17 16:56:53 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -75, MAC: 54EF44E0C40F, ADV: 043e1e020100000fc4e044ef54120201060e1695fe10598d0a190fc4e044ef54b5
2021-02-17 16:56:54 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -69, MAC: 54EF44E0C40F, ADV: 043e29020100000fc4e044ef541d020106191695fe58598d0a1a0fc4e044ef54d8c96973000000c04efff0bb
2021-02-17 16:56:57 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -75, MAC: 54EF44E0C40F, ADV: 043e1e020100000fc4e044ef54120201060e1695fe10598d0a1b0fc4e044ef54b5
2021-02-17 16:57:24 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -72, MAC: 54EF44E0C40F, ADV: 043e2b020100000fc4e044ef541f0201061b1695fe58598d0a1c0fc4e044ef54168d72a7823b0000006ef94f67b8
2021-02-17 16:57:55 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -67, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a1d0fc4e044ef54bd
2021-02-17 16:57:55 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -67, MAC: 54EF44E0C40F, ADV: 043e29020103000fc4e044ef541d020106191695fe58598d0a1e0fc4e044ef540d9685da000000f25a320fbd
2021-02-17 16:57:58 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -64, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a1f0fc4e044ef54c0
2021-02-17 16:58:12 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -71, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a210fc4e044ef54b9
2021-02-17 16:58:12 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -66, MAC: 54EF44E0C40F, ADV: 043e2b020103000fc4e044ef541f0201061b1695fe58598d0a220fc4e044ef54c4061feb1d93000000d289c3a0be
2021-02-17 16:58:18 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -64, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a240fc4e044ef54c0
2021-02-17 16:58:29 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -67, MAC: 54EF44E0C40F, ADV: 043e29020100000fc4e044ef541d020106191695fe58598d0a250fc4e044ef544f1a8898000000da567336bd
2021-02-17 16:58:32 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -73, MAC: 54EF44E0C40F, ADV: 043e1e020100000fc4e044ef54120201060e1695fe10598d0a260fc4e044ef54b7
2021-02-17 17:00:01 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -68, MAC: 54EF44E0C40F, ADV: 043e2b020100000fc4e044ef541f0201061b1695fe58598d0a270fc4e044ef540755250a96910000002c335e4abc
2021-02-17 17:00:13 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -67, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a280fc4e044ef54bd
2021-02-17 17:00:52 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -70, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a2a0fc4e044ef54ba
2021-02-17 17:00:52 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -71, MAC: 54EF44E0C40F, ADV: 043e2b020103000fc4e044ef541f0201061b1695fe58598d0a2b0fc4e044ef54aa651a683a9e000000406e14adb9
2021-02-17 17:02:23 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -67, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a370fc4e044ef54bd
2021-02-17 17:02:35 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -76, MAC: 54EF44E0C40F, ADV: 043e2b020103000fc4e044ef541f0201061b1695fe58598d0a380fc4e044ef54830a2352cdcf000000fab9f997b4
2021-02-17 17:02:48 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -71, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a3a0fc4e044ef54b9
2021-02-17 17:02:49 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -72, MAC: 54EF44E0C40F, ADV: 043e2b020103000fc4e044ef541f0201061b1695fe58598d0a3b0fc4e044ef5421abfd9d2c7b00000031a28a9cb8
2021-02-17 17:02:54 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -73, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a3d0fc4e044ef54b7
2021-02-17 17:02:57 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -63, MAC: 54EF44E0C40F, ADV: 043e29020100000fc4e044ef541d020106191695fe58598d0a3e0fc4e044ef5469b08e040000006a94620ec1
2021-02-17 17:03:00 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -62, MAC: 54EF44E0C40F, ADV: 043e1e020103000fc4e044ef54120201060e1695fe10598d0a3f0fc4e044ef54c2
2021-02-17 17:03:00 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -62, MAC: 54EF44E0C40F, ADV: 043e29020103000fc4e044ef541d020106191695fe58598d0a400fc4e044ef54e0d8f7dc000000115231adc2
2021-02-17 17:04:02 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -69, MAC: 54EF44E0C40F, ADV: 043e29020100000fc4e044ef541d020106191695fe58598d0a450fc4e044ef54122004ef0000004226519dbb
2021-02-17 17:04:04 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -68, MAC: 54EF44E0C40F, ADV: 043e29020100000fc4e044ef541d020106191695fe58598d0a460fc4e044ef54ba924a87000000452a5ccdbc
2021-02-17 17:04:07 INFO (Thread-108) [custom_components.ble_monitor] BLE ADV from UNKNOWN: RSSI: -77, MAC: 54EF44E0C40F, ADV: 043e1e020100000fc4e044ef54120201060e1695fe10598d0a470fc4e044ef54b3

**Comment by Ernst79** [comment] 2021-02-17 16:16
The messages are encrypted. Can you send me the encryption key? You can find it with [Xiaomi Cloud Token Extractor](https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor). I need the BLE KEY from the output of this tool (and you will need it later when you add the sensor).

**Comment by andriensis** [comment] 2021-02-17 16:19
FDD8CE9C08AE7533A79BDAF0BB755E96

Would you mind linking a guide explaining how to decrypt those adv payloads with the key?
Thanks!

**Comment by Ernst79** [comment] 2021-02-17 16:33
Thanks, the result:

{'rssi': -69, 'mac': '54EF44E0C40F', 'type': 'RTCGQ02LM', 'packet': 23, 'firmware': 'Xiaomi (MiBeacon advertisements)', 'data': True, 'motion': 1, 'motion timer': 1, 'light': 0}

I don't have a guide, but I have a python script that does basically the same as the `parse_raw_data` in `__init__.py`. If you want, I can send you the file, to play around with. 

I will prepare an update, but we will need to check it the motion and light sensor work as expected. As you see it is a combined message which basically says `motion detected`, turn on the `motion timer` (again) and it is `dark` in the room. Hopefully, your sensor works the same as the one that is already in the code.

**Comment by andriensis** [comment] 2021-02-17 16:36
Sure, you could send me the file if it's not too much trouble.

I can definitely help you decrypt those messages and give you more detailed logs (like trying to turn off/on the light and giving you the ADV result)

**Comment by Ernst79** [comment] 2021-02-17 19:17
First some explanation of the messages that are send. The result is the current implementation, which is based on already existing sensors, like a motion sensor and a button.

The short message do not contain data. 

The first long message is a message of type `0F 00`, which is either `00 00 00` or `00 00 01`. 
```
result:  {'rssi': -69, 'mac': '54EF44E0C40F', 'type': 'RTCGQ02LM', 'packet': 23, 'firmware': 'Xiaomi (MiBeacon advertisements)', 'data': True, 'motion': 1, 'motion timer': 1, 'light': 0}
```
The second long message is a message of type `01 10` which is either `00 00 00` or `00 00 01` (probably, there are sensors that send `000002` for long press)
```
result:  {'rssi': -72, 'mac': '54EF44E0C40F', 'type': 'RTCGQ02LM', 'packet': 28, 'firmware': 'Xiaomi (MiBeacon advertisements)', 'data': True, 'button': 'no press'}
```
The third long message is of type `18 10`, which is either `00` or `01`. 
```
result:  {'rssi': -67, 'mac': '54EF44E0C40F', 'type': 'RTCGQ02LM', 'packet': 30, 'firmware': 'Xiaomi (MiBeacon advertisements)', 'data': True, 'light': 0}
```

**Comment by Ernst79** [comment] 2021-02-17 19:40
The official meaning according to https://iot.mi.com/new/doc/embedded-development/ble/object-definition (thanks to google translate)

`0F 00` =  Someone is moving (with light)
`01 10` = button
`18 10` = Light intensity

**Comment by andriensis** [comment] 2021-02-17 20:23
I'm testing it right now.

It looks like the light sensor works perfectly.
Motion sensor also works but maybe sometimes there's a small gap of a few seconds when it says there's no movement detected (I'm moving my hand in front of the sensor to let it records continuos movement).
Maybe I should try and play around with the `reset_timer`

The button entity also works and reports a single press.
Battery state is unknown at the moment, I will let you know if it changes.

**Comment by andriensis** [comment] 2021-02-18 07:52
Battery was updated a few hours after pairing the device during the night. It reports as 80%, not sure if it's that accurate.

After further investigation it looks like the light sensor doesn't work that great (reports as dark when the room is light and takes some time to update its state) but I guess that's related to the sensor itself.

**Comment by Ernst79** [comment] 2021-02-18 10:28
Battery is never very accurate, they use some scale to determine the percentage, like 0% = 2,5V 100% is 3,x V, something like that. 

Is it only the light sensor that isn't accurate? Or also the motion sensor?

**Comment by andriensis** [comment] 2021-02-18 10:30
Motion sensor works perfectly with a timeout of 35 seconds.
Light sensor works but it looks like it has a low sensitivity and sometimes when motion is detected it reports back as **dark**

**Comment by Ernst79** [comment] 2021-02-18 10:37
Ok, as you see above, we use two messages for light. The other motion sensor uses 0F 00 == 100 to detect light, but it seems in your device, it uses 1, not 100. 

Just look up the following part in `__init__.py` and change == 100 to == 1

```
        def obj0f00(xobj):
            (light,) = LIGHT_STRUCT.unpack(xobj + b'\x00')
            return {"motion": 1, "motion timer": 1, "light": 1 if light == 100 else 0}
```

**Comment by andriensis** [comment] 2021-02-18 15:32
`light": 1 if light == 1 else 0` didn't help much.

I also tried `light": 1 if light == 1 or light == 100 else 0` and this looked better but not really that reactive, sometimes it takes a long time to detect light from dark (like 30 seconds).

I also tried the other way around
`light": 0 if light == 0 else 1`
and this is the one that looks better out of all of them.

So maybe I'm thinking there are some intermediary values? Like 0.7, 0,5 etc. 
If you can provide a link on how to check logs on hassio I can try posting them.

**Comment by Ernst79** [comment] 2021-02-18 15:55
You can add the following logger line to def parse_raw_message to get the data messages in the HA logs in init.py. This will show all ble messages

```
def parse_raw_message(self, data):
    _LOGGER.error("Data: %s", data.hex())
    """Parse the raw data."""
```

you can also put it in the slightly lower in the Xiaomi parser, to only have the Xiaomi messages. Xiaomi messages can be recognized by 1695fe somewhere in the advertisement

**Comment by Ernst79** [comment] 2021-02-18 19:46
I made a new update, which (temporary) adds an additional illuminance sensor. This show the real value send by the sensor with the 0F 00 messages. Copy const.py and `__init__.py` to test from the same branch. This might make it easier to understand what this message means. Make sure you set decimals to 1 or 2.

**Comment by Ernst79** [comment] 2021-02-18 20:05
Oh, sorry, that won’t work, due to the averaging of sensor

**Comment by andriensis** [comment] 2021-02-19 07:11
What do you mean "with a relatively short period of 15 seconds"?

**Comment by andriensis** [comment] 2021-02-19 07:23
I set the period in BLE monitor options to 15

![image](https://user-images.githubusercontent.com/28559869/108471213-5c549600-728b-11eb-886a-f4e8fab2131c.png)

The illuminance entity shows up but reports its state as "unknown" even after trying to mess with the sensor (dark, light, motion...)

**Comment by Ernst79** [comment] 2021-02-19 17:34
I’m a few days away, so it’s difficult to help you right now. I get back on this on Sunday or Monday. Did you copy `__init__.py` as well?

**Comment by Ernst79** [comment] 2021-02-19 17:47
Ah, sorry, I found the error. I forgot to tell the sensor that it is a measuring sensor. Can you download `__init__.py` again. Should be working now.

**Comment by andriensis** [comment] 2021-02-19 18:15
Will do, thanks.

**Comment by andriensis** [comment] 2021-02-19 19:43
Looks like the value is either 0 or 256.
I also tried decreasing the report value to 5 seconds and results are the same.

![image](https://user-images.githubusercontent.com/28559869/108553550-2519cf80-72f3-11eb-8c70-66cd428fcfb4.png)

**Comment by Ernst79** [comment] 2021-02-19 19:50
I will change it to >= 100, such that it works for both sensors.


```
        def obj0f00(xobj):
            (light,) = LIGHT_STRUCT.unpack(xobj + b'\x00')
            return {"motion": 1, "motion timer": 1, "light": 1 if light >= 100 else 0}
```

but can you confirm that 256 is light in the room and 0 is dark in the room?

**Comment by andriensis** [comment] 2021-02-20 10:08
Actually not.
It looks like it's almost always 256  with some brief spikes to 0.
It's been on all night, light sensor reported as dark but lux still 256. Now there's light in the room (and the light sensor reports as light detected) but that value is still 256.

**Comment by Ernst79** [comment] 2021-02-20 10:39
I know from the other motion sensor that 0F 00 messages are only send when you move. So, if you moved with the light on, and then go to bed, it will stay 256 till you move again. The 18 app messages will update the light state as well, every 5 minutes probably. But we are going to remove the illumination sensor anyway, we just needed to get the correct value.

Question is, is the light sensor working correct now?

**Comment by andriensis** [comment] 2021-02-20 11:46
I haven't tested the` >= 100` yet (will do it later today).
So far the best results were given by inverting the if condition (0 if light is 0 else 1)

I'll let you know as soon as possible if the solution you suggested works as well.

**Comment by Ernst79** [comment] 2021-02-20 12:02
It should give the same result, I think, but there is a new sensor that actually does use the value to report lux values. It’s not implemented yet, but if we can keep the 100 in, we can adjust it slightly in the future.

**Comment by rezmus** [comment] 2021-02-20 15:33
just keep in mind that some other sensors like qingping motion sensor send event.15 (0x0f00) with lux data (not just 0/1 like this sensor).

**Comment by Ernst79** [comment] 2021-02-20 16:22
Yes, that was what I was talking about. At this moment, we have one sensor that uses 0/100 and this one uses 0/256. The one you reported about on the HA forum uses the real lux value. Not sure what lux value actually can be assumed to be limit between dark and light. If we are lucky, it’s a value below 100 lux. But even if it is higher, we can make it work.

**Comment by rezmus** [comment] 2021-02-20 16:28
i mean you should expose this value somehow ;) when it's dark i have 0, cloudy winter bright over 1k, with flashlight i managed to get 30-50k ;)

**Comment by Ernst79** [comment] 2021-02-20 16:31
Yes, sure. For sensors that do actually send lux, I will add an illuminance sensor for sure, which reports the lux value. But for this one, that doesn’t make sense.

**Comment by andriensis** [comment] 2021-02-20 17:57
I tested with >= 100 but again, it only works if there's a lot of light. 
Not sure what we can do anymore other than checking the item specific advertisements. 

I have no idea how to do that on hassio

**Comment by Ernst79** [comment] 2021-02-20 18:14
You said that the other way around did work.

`light": 0 if light == 0 else 1`

I don’t really see how this is any different compared to

`light": 1 if light >= 100 else 0`

In both cases 0 results in 0 and 256 results in 1.

**Comment by Ernst79** [comment] 2021-02-20 18:26
This is how the xiaomigateway3 component has it implemented.

```
    elif eid == 0x0F:  # 15
        # Night Light 2: 1 - moving no light, 100 - moving with light
        # Motion Sensor 2: 0 - moving no light, 256 - moving with light
        # Qingping Motion Sensor - moving with illuminance data
        value = int.from_bytes(data, 'little')
        return (
            {'motion': 1, 'illuminance': value}
            if pdid == 2691 else
            {'motion': 1, 'light': int(value >= 100)}
        )
```

2691 is Qingping Motion Sensor (CGPR1)

**Comment by andriensis** [comment] 2021-02-21 13:48
`{'motion': 1, 'light': int(light >= 100)}`
This seems to work okay.

I'm starting to think the "issues" were caused by the sensor itself if it's not too reactive to light changes.

**Comment by Ernst79** [comment] 2021-02-22 14:47
1.1.1-beta has been released. Please remove the illumination sensor after the restart (should become unavailable after a restart).

**Comment by andriensis** [comment] 2021-02-22 15:23
Just a minor issue with the README change in the pull request.
It looks to me the light sensor is updated when it detects a light change, not every five minutes. So if it's dark (and it's reporting dark) and I turn one light if reports as light detected instantly even if there's no movement detected.

**Comment by Ernst79** [comment] 2021-02-22 15:25
ah, ok, I copied that from the other motion sensor. I'll change that. Thanks!

**Comment by andriensis** [comment] 2021-02-22 15:40
Thank you for your work!
Everything seems to work okay, I'll confirm tomorrow (will do some tests when the sun is down 😃 )

**Comment by andriensis** [comment] 2021-02-23 10:15
Everything is working fine!

**Comment by Ernst79** [comment] 2021-02-23 10:28
Released as version 1.1.1

**Closed by Ernst79** 2021-02-23 10:28 UTC

**Comment by Ernst79** [comment] 2021-02-23 21:05
@andriensis Could you do me a favor and check if your sensor keeps working with 1.1.2-beta. I've added the CGPR1 sensor, which is also a motion sensor. I had to add illumination for this sensor, as it measures in lux, but I want to confirm that your sensor keeps working as it was (so only light sensor, no illumination sensor should show up).

**Comment by andriensis** [comment] 2021-02-24 07:36
Motion entity is not working and is stuck at “not available”
Everything else seems to work

**Comment by Ernst79** [comment] 2021-02-24 07:53
Hmm, that strange. 

Could you try the following change. In `__init__.py` on line 539, can you change 

```
            b'\x0F\x00': (obj0f00, True, False),
```
to 
```
            b'\x0F\x00': (obj0f00, True, True),
```

and do a restart. If it doesn't work after that, can you check if there are errors in the log? thanks!

**Comment by andriensis** [comment] 2021-02-24 07:59
Actually, nevermind.
The motion sensor started working like five minutes later than the light sensor/etc. 
It never happened before so I thought it wasn't working at all.

Sorry about that.

**Comment by Ernst79** [comment] 2021-02-24 08:06
no problem. Thanks for the feedback anyway.

**Comment by FrancYescO** [comment] 2021-03-29 11:02
Hello, it's possibile to get this sensor data without having a xiaomi gateway?

**Comment by Ernst79** [comment] 2021-03-29 11:52
Don't think so, as you will need to get an encryption key, which is generated when you add it to MiHome. I think the sensor communicates with the xiaomi gateway, so not directly to your phone. But you can try to see if you can add the sensor to the MiHome app without the gateway. I don't think this will work, but just try to make sure.

Some sensors like LYWD03MMC can get a key without MiHome on this [website](https://github.com/pvvx/ATC_MiThermometer), but this website does not support you sensor. So, if you can't add it to MiHome, it won't work without gateway.

**Comment by FrancYescO** [comment] 2021-03-29 12:07
![immagine](https://user-images.githubusercontent.com/4574593/112833483-16af9800-9097-11eb-8306-e7da2b4354b2.png)
:(

already tried the ATC website, but after pairing i cannot do the activation.. also i assume without a gateway there is nothing (neither encrypted) to sniff

i wrongly bought this device (assuming it was zigbee) and i have no gateway for set it up :(

**Comment by andrewjswan** [comment] 2021-03-29 12:22
> Hello, it's possibile to get this sensor data without having a xiaomi gateway?

Yes, just add it to MiHome (and get paring key) then add it to HA with paring key ...

**Comment by FrancYescO** [comment] 2021-03-29 13:00
Ok i was trying to add the v1 that ask for a gateway, after switching to china mainland v2 appeared in the app and i'm able to add it, now just need to figure out how to get the pairing key, thank you.

**Comment by andrewjswan** [comment] 2021-03-29 13:31
Just in case, each binding changes the key. :)

**Comment by andrewjswan** [comment] 2021-03-29 13:33
> and i have no gateway for set it up

The gateway is needed to connect the sensor to the cloud, if there is no gateway, you can only get data from the sensor by connecting to it. But if the sensor is connected to Home Assistant, it also doesn't need the gateway and all data will be in Home Assistant.

**Comment by FrancYescO** [comment] 2021-03-29 13:59
Starting to be challenging.. I've added the sensor to the mi home modded app but it does not show me any data from the sensor.. neither i see a pairing key in the `vevs` folder.. i hope the token_extractor.py can help me to get the key

**Comment by andrewjswan** [comment] 2021-03-29 14:12
> neither i see a pairing key in the `vevs` folder

Need create vevs/logs folder, then remove sensor from MiHome, and add it again, in vevs/logs/misc/pairings.txt  should be paring keys (**Bindkey**) ...

**Comment by FrancYescO** [comment] 2021-03-29 14:21
got the key via https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor

now i'm trying to add to this extension but integration > Passive BLE Monitor > add device > insert MAC and key click submit, nothing happens.

**Comment by andrewjswan** [comment] 2021-03-29 15:16
@Ernst79 maybe need add https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor to FAQ?

**Comment by Ernst79** [comment] 2021-03-29 15:59
It’s already in the FAQ, as the number 1 solution to get your key.

**Comment by asdkjasdfla** [comment] 2022-12-05 22:19
Can someone please explain how can I get the luminance value from this sensor in home assistant?

**Comment by FrancYescO** [comment] 2022-12-09 09:44
> Can someone please explain how can I get the luminance value from this sensor in home assistant?

this sensor does not comunicate lux, just a boolean state via `binary_sensor.ble_light_*` entity
