### ISSUE TITLE
Not available in the integration page after updating HACS to 1.19.0

### ISSUE THREAD

**Issue by Tomlap123** [custom-components/ble_monitor#615] opened 2022-01-08 14:01 UTC
![image](https://user-images.githubusercontent.com/59482532/148646806-75a6c8d2-3ee9-4e40-958d-1e1a8075e982.png)
![image](https://user-images.githubusercontent.com/59482532/148647034-3af948b2-be9a-4007-9ddc-4a725ef92a34.png)
![image](https://user-images.githubusercontent.com/59482532/148647039-2889f104-6e0d-4529-84bc-fb4fae669b45.png)

**Comment by Ernst79** [comment] 2022-01-08 14:20
try to clear your cache of your browser, hit F5 a couple of times. Most of the times this help after an update.

**Comment by Amskii** [comment] 2022-01-08 15:21
I'm seeing the same thing after updating to 6.8.0. The whole Passive BLE monitor also completely stopped working and I got the following error in logs:

Logger: homeassistant.setup
Source: setup.py:153
First occurred: 17:14:05 (1 occurrences)
Last logged: 17:14:05

Setup failed for ble_monitor: Integration not found.

**Comment by Ernst79** [comment] 2022-01-08 15:27
I just upgraded myself, don't see any issue. 

Can you check if the folder `/custom_components/ble_monitor` still exists?

**Comment by Competizione** [comment] 2022-01-08 15:32
I can confirm this Issue with HA 2021.12.3 after updating Passive BLE monitor to 6.8.0
Found path \custom_components\ble_monitor\ble_monitor\... so just moved files to \custom_components\ble_monitor\... and fixed issue.

**Comment by Amskii** [comment] 2022-01-08 15:36
> I can confirm this Issue with HA 2021.12.3 after updating Passive BLE monitor to 6.8.0 Found path \custom_components\ble_monitor\ble_monitor... so just moved files to \custom_components\ble_monitor... and fixed issue.

Exactly what happened with my installation too and the moving the files fixed the issue. I'm running HA 2021.12.8.

**Comment by Ernst79** [comment] 2022-01-08 15:39
hmm, very strange. Not sure if this is an issue in HACS or in BLE monitor. 
Also strange that it didn't happen in my case.

**Comment by Amskii** [comment] 2022-01-08 15:42
Definitely seems like a bit of an odd issue. I just updated BLE monitor to 6.7.2 a few hours ago and it worked fine.

**Comment by luisleonardo** [comment] 2022-01-08 15:43
Just upgraded and also had the same issue.

Moving all the files from "\custom_components\ble_monitor\ble_monitor" to "\custom_components\ble_monitor" and reboot solved the issue.

**Comment by Ernst79** [comment] 2022-01-08 16:00
Ah, I can confirm it. With HACS 1.18.0, it all works fine, HACS 1.19.0 will cause the issue. I will fill in an issue for HACS

**Comment by Ernst79** [comment] 2022-01-08 16:04
Yes, HACS 1.19.1 solves the issue. Just update HACS first, restart HA and than update BLE monitor again. 

Files will than move back to the place where they should be.

**Comment by groto27** [comment] 2022-01-08 17:08
> Yes, HACS 1.19.1 solves the issue. Just update HACS first, restart HA and than "redownload" BLE monitor again by clicking on the three dots --> "redownload"
> 
> Files will than move back to the place where they should be.

This works for me. Thanks

**Comment by Ernst79** [comment] 2022-01-10 07:16
Fixed in HACS 1.19.2, closing this issue

**Closed by Ernst79** 2022-01-10 07:16 UTC
Labels: bug
