### ISSUE TITLE
MUE4094RT 'reset timer' not being observed

### ISSUE THREAD

**Issue by kanemari** [custom-components/ble_monitor#496] opened 2021-09-08 07:07 UTC
Hi there,

I have been using the integration successfully with the Xiaomi Philips night lights for many months, but have noticed recently that the sensors do not switch off after triggered. I was using the 'reset timer' attribute to turn the sensor off after 15 seconds (since the device doesnt send any BLE notification to indicate the light is off) but that doesn't seem to be working anymore.

Has anything changed?

Thanks.

**Comment by gabrymed** [comment] 2021-09-08 07:44
Same problem here, it worked well for months but now resetting timer (i use reset timer=20sec)  it seems it doesn't  work.

**Comment by Ernst79** [comment] 2021-09-08 09:16
I will look into it a.s.a.p.

**Comment by Ernst79** [comment] 2021-09-08 10:19
@Thrilleratplay do you have an idea why the docs for the MUE4094RT isn't showing up? The file is there. 

https://github.com/custom-components/ble_monitor/blob/master/docs/_devices/MUE4094RT.md

**Comment by Ernst79** [comment] 2021-09-08 11:00
Should be fixed in 5.2.1. Please leave the issue open till I figured out the missing docs.

**Comment by Thrilleratplay** [comment] 2021-09-08 11:20
@Ernst79 I think it is indentation of `- property: motion` but I may not be able to test this for a few hours.  I submitted a patch if that is the cause.

**Closed** 2021-09-08 12:48 UTC
