### ISSUE TITLE
Add manualy LYWSD03MMC 

### ISSUE THREAD

**Issue by Cebulman** [custom-components/ble_monitor#588] opened 2021-12-23 15:19 UTC
I add manyaly in gui LYWSD03MMC  oryginal fw and report me this :

Logger: custom_components.ble_monitor.ble_parser.xiaomi
Source: custom_components/ble_monitor/ble_parser/xiaomi.py:820
Integration: Passive BLE monitor (documentation, issues)
First occurred: 15:23:48 (13 occurrences)
Last logged: 16:09:43

No encryption key found for device with MAC A4:C1:38:DE:4E:48

and this : 

Logger: custom_components.ble_monitor.ble_parser.xiaomi
Source: custom_components/ble_monitor/ble_parser/xiaomi.py:833
Integration: Passive BLE monitor (documentation, issues)
First occurred: 15:36:04 (4 occurrences)
Last logged: 15:36:11

Decryption failed: MAC check failed

I can't remove the sensor from gui and the Passive BLE monitor service: cleanup_entries  
I can not add again, but with Telink Flasher it connects and works well

**Comment by Ernst79** [comment] 2021-12-26 09:15
What do you want to do, remove it or add it?

note that Telink Flasher can reset the encryption key, so if you use that tool, make sure you copy the new encryption key into BLE monitor

I assume you have flashed it with ATC firmware, is it? In the firmware settings with the online telink flasher, you can choose to remove or add the encryption key. Make sure it matches BLE monitor settings

**Comment by Cebulman** [comment] 2021-12-26 17:06
Delete , Atc fw connect normal and no report    Problems but stay in ble integration old entry

**Comment by Ernst79** [comment] 2021-12-27 11:21
Try the following

In the `--Devices--` menu, select the device you want to delete. Click `submit` and the options menu for this device will show up. Select `Delete device` at the bottom and click `submit` twice. 

![image](https://user-images.githubusercontent.com/24375847/147466832-89f84211-7d69-4fe7-a236-0cd83d4d11bf.png)

Next, go to the integration menu and select 'Devices', like this

![image](https://user-images.githubusercontent.com/24375847/147466880-97997960-e1b9-4a0e-8f94-4918f75bafc8.png)

Click on the old device, if still there and click on each sensor, like this

![image](https://user-images.githubusercontent.com/24375847/147466964-b7471128-3767-4eab-a5e9-757de57e9972.png)

Next, delete the sensor, repeat for each sensor. 

![image](https://user-images.githubusercontent.com/24375847/147466997-705f0270-0ce1-4216-b7af-2b51b2ab0f2e.png)

If you are finished with all sensors, run the Passive BLE monitor service: `cleanup_entries`

**Comment by Cebulman** [comment] 2021-12-27 12:43
Hey, we didn't understand each other. I mean, I manually added the mac address in gui because I couldn't detect it automatically.
After this process, despite adding the secret key in gui, it also did not work, so I decided to remove the device as you write, unfortunately it can not be removed, so it bursts with errors during start-up. I changed the software to atc and connected normally, it works normally. The only question is how to remove a manually added sensor? the advice you wrote does not work

**Comment by Ernst79** [comment] 2021-12-27 13:19
hmmm, strange. Normally the `Delete device` button should do the trick. Perhaps try a restart first, and try again. It that doesn't help, I'm afraid that you have to remove BLE monitor, restart HA and reinstall it again.

**Comment by Cebulman** [comment] 2021-12-27 15:50
I have already done that, it did not help, I thought it would be possible without uninstalling, thanks and greetings, this is a good project, keep it up

**Comment by Ernst79** [comment] 2021-12-27 18:59
I just tried it myself, I was able to delete an old device just fine. Didn't even need the cleanup_entries service. I think it won't work in your case, because it is automatically rediscovered. Try to disable `discovery` temporary, and delete the sensor afterwards. Also make sure you use only one advertisement type in the firmware of the sensor. ATC firmware is able to set it to "all" advertisement types, which will be confusing for HA, as it will receive both advertisements with and without encryption.

**Comment by Cebulman** [comment] 2021-12-27 19:10
I'll try tomorrow well. I remember when I added it, I had to enter, for example, "A6: E4" and how did you write? with or without a colon when adding?

**Comment by Ernst79** [comment] 2021-12-27 19:17
Normally with colon

![image](https://user-images.githubusercontent.com/24375847/147500898-61ad4578-4085-49aa-a622-33028b1a9250.png)

**Comment by Cebulman** [comment] 2021-12-27 20:48
> Normally with colon
> 
> ![image](https://user-images.githubusercontent.com/24375847/147500898-61ad4578-4085-49aa-a622-33028b1a9250.png)



> Normally with colon
> 
> ![image](https://user-images.githubusercontent.com/24375847/147500898-61ad4578-4085-49aa-a622-33028b1a9250.png)

same, will try tomorrow

**Comment by Ernst79** [comment] 2022-01-04 15:17
Any update?

**Comment by Cebulman** [comment] 2022-01-04 16:22
I tried and it can not be removed - I did not uninstall, therefore I will have to reconfigure everything and I do not have time to do it, I will let you know

**Comment by aletzi1** [comment] 2022-01-07 06:12
I also have same issue with deleting device. I tried to add Series 20000 Oral-B and its not supported yet. 

Now i cant delete my Oral-B mac addresses from devices list, feels like delete button doesnt work with unsupported devices. There is no entitites added HA, only mac-addresses, so i could not delete entitites...

![Screenshot_20220107-080853](https://user-images.githubusercontent.com/66028464/148500320-5e7ffff1-0e19-4fbb-853c-3afb95a225df.jpg)

I havent install BLE monitor again yet.

**Comment by Ernst79** [comment] 2022-01-07 07:13
Illlook into it, just one question, did you add these sensors manually, by entering the Mac addresses?

BTW. If you want we can try to add this oral-b 20000 device to BLE monitor, the faq has a section how to get some ble data, which we need to add support.

**Comment by aletzi1** [comment] 2022-01-07 07:33
> Illlook into it, just one question, did you add these sensors manually, by entering the Mac addresses?
> 
> BTW. If you want we can try to add this oral-b 20000 device to BLE monitor, the faq has a section how to get some ble data, which we need to add support.

I added these sensors manually with GUI.
I'll take a look how to provide ble data to you, so you can add support for more devices, sometime in the future. :)

**Comment by Ernst79** [comment] 2022-01-07 19:50
I can confirm that manually added MAC addresses of non-existing devices can't be deleted. I have to dig into it why not. .....

**Comment by Ernst79** [comment] 2022-01-09 15:51
Deleting of manually added devices should be fixed in 6.9.0-beta.

**Closed** 2022-01-10 07:15 UTC
Labels: bug
