### ISSUE TITLE
New device_id for Switchbot Meter Plus

### ISSUE THREAD

**Issue by gilcu3** [custom-components/ble_monitor#953] opened 2022-07-17 15:59 UTC
### What happened?

My new switchbot meter plus sensor began providing `device_id = 0xc069` instead of `0x0069`. If this value is added to the list of accepted values, everything works correctly.

### Sensor type

Switchbot

**Comment by Ernst79** [comment] 2022-07-19 15:16
Fixed in 9.0.2. thanks for reporting

**Comment by DigiH** [comment] 2022-07-23 00:17
Hi @Ernst79, sorry to peak in again :blush: but doesn't including the **Status** byte into the **device_id** not possibly eventually  just require including all possible variations **00-FF**?

Admittedly, **Bit[7:4] - Reserved** might not use all bits, but even for a user adding the Meter (Plus) to one or more groups **Bit[3:0]** would mess with the **device_id**.

https://github.com/OpenWonderLabs/SwitchBotAPI-BLE/blob/latest/devicetypes/meter.md

Hope I'm not overstepping.

**Comment by Ernst79** [comment] 2022-07-23 07:30
I see, thanks. I was not aware of this. I guess we can define the device based on the second byte only. I’ll reopen this issue and will fix it.

**Comment by DigiH** [comment] 2022-07-23 10:41
I even spotted a mistake with the temperature decimal not ignoring the alters bits in our decoder when going through this again.

Win win for both of us ;)

**Comment by Ernst79** [comment] 2022-07-25 14:03
9.0.7 has been released, thanks for the input

**Comment by DigiH** [comment] 2022-07-25 16:11
Sorry @Ernst79 , I really don't want to be a pain, but I think your temperature could do with a little tweak as well.

In your syntax probably masking & 127 instead of the -128, and if conditioning when bit 7 is 0 = zub zero  temperatures * -1, otherwise as is, hence your current -128 only allowing for +0ºC temps and having to subtract 128 because bit 7 is 1.

And also the same problem I discovered above, with your byte2 also being messed up by bits 4-7, as soon a user has set alerts, encoded in those bits.

Unless I'm totally misreading your decoding.

I've tried to include all those eventualities in our test cases

https://github.com/theengs/decoder/blob/development/tests/BLE/test_ble.cpp#L125

https://github.com/theengs/decoder/blob/development/tests/BLE/test_ble.cpp#L364

**Comment by Ernst79** [comment] 2022-07-25 18:56
Any improvements are always welcome. I’ll fix that later, will probably not be the coming weeks, due to other things I have to do. Will reopen the issue to not forget

**Comment by Ernst79** [comment] 2022-07-26 14:45
@DigiH Do you know how to check the 7th bit? Is this correct?

```python
        (batt, temp_frac, temp_int, humi) = unpack("<BBBB", xvalue)
        batt = (batt & 127)
        temp_sign = temp_int & 64
        if temp_sign == 0:
            temp = float(temp_int & 127)+float(temp_frac / 10.0)
        else:
            temp = -1 * (float(temp_int & 127) + float(temp_frac / 10.0))
        humi = (humi & 127)
```

**Comment by DigiH** [comment] 2022-07-26 15:39
@Ernst79, shouldn't it be & 128, the one last highest 8th, i.e. bit 7 (counting 7-0 from right), left most bit left from **temp_int**, the rest being the actual temperature integer you get with **temp_int & 127**

And temp_frac with & 15 ?!? to mask it from the alert bits.

With the sub zero you can test the above with one of our test cases, linked above, which should also give you the **-25.3 ºC**

Also included are several test cases with different alert bits set.

**Comment by Ernst79** [comment] 2022-07-26 16:35
Ah, yes, you are totally right, bit 7 is the 8th bit. I'm always confused with these bitwise operations. Its good that I asked you to have a look 😄. 

I also added the temperature scale conversion (HA assumes Celsius by default)

```python
        (batt, temp_frac, temp_int, humi) = unpack("<BBBB", xvalue)
        batt = (batt & 127)

        temp_sign = temp_int & 128
        temp_scale = humi & 128
        temp = float(temp_int & 127) + float((temp_frac & 15) / 10.0)
        if temp_sign == 0:
            # Negative temperature
            temp = -1 * temp
        if temp_scale == 1:
            # Temperature in Fahrenheit, convert to Celsius
            temp = (temp - 32) * 5/9

        humi = (humi & 127)
```

**Comment by DigiH** [comment] 2022-07-26 16:47
Yes, it can always get a bit confusing with the bits ;)

Looks good now.

I've actually left out the temperature scale as in by brief testing of it it doesn't actually change any of the transmitted values - temp always still reported in Celsius - but I assume it is a bit only set to show how the actual Meter (Plus) is showing the temp and how the SwitchBot app should then also show it.

Please let me know if have found otherwise ;) 

… you got me worried now, just testing again here ;P

**Comment by DigiH** [comment] 2022-07-26 16:52
No, definitely like I said, only indicating how the device is showing it, and probably then how the app should show it.

I even specifically implemented two test cases exactly for this

{"Switchbot_Meter", "0d00", "servicedata", "5400544599**38**"},
{"Switchbot_Meter", "0d00", "servicedata", "5400d40299**b8**"},

So you can also take it out of your code to keep in leaner :)

**Comment by DigiH** [comment] 2022-07-26 17:39
Yes, from the user manuals of Meter and Meter Plus
<img width="509" alt="Screenshot 2022-07-26 at 19 37 03" src="https://user-images.githubusercontent.com/17110652/181073935-0a4a7589-917d-431a-bb7a-20b4c53b8a24.png">

<img width="380" alt="Screenshot 2022-07-26 at 19 36 42" src="https://user-images.githubusercontent.com/17110652/181073954-d9dd66fe-14dc-41ed-bf8c-cb9a7ef3505c.png">

So the temperature is definitely always transmitted in Celsius, as Bit[6:0] would never be able to transmit any values over 127ºF

It's only for the indication of how the Meter shows it locally.

**Comment by Ernst79** [comment] 2022-07-26 18:21
Ok, thanks. I don’t have the device myself, so your help is much appreciated. Will create a new version, without the Fahrenheit conversion. thanx again.

**Comment by DigiH** [comment] 2022-07-26 18:27
Anytime :)

I don't have it either ;) but it just seem logical to me with the above reasons.

**Comment by DigiH** [comment] 2022-07-26 18:51
I see you've used the same sub zero temp test case as us ;) 

While the calculation is correct and everything, with the screenshots from the manuals I just posted it also is a bit out of the actual measuring range of the Meter (Plus), which only goes down to -20ºC :stuck_out_tongue_winking_eye: LOL Still fine for a test calculation.

**Comment by Ernst79** [comment] 2022-07-26 18:56
haha, LOL. I just copied your test service data into one of the raw advertisements I had

**Comment by DigiH** [comment] 2022-07-26 19:01
I know how this happened, I usually go about the same way creating test cases. I copied the test case above, with 25.8ºC, the changed the one negative value bit to test just that, it worked, then I also changed the decimal and humidity a bit to make it all different from the above, but completely ignoring the unrealistic temp :)

1technophile however has the device and confirmed the negative temperatures with a quick freezer test, so all is fine :)

**Closed** 2022-08-12 18:32 UTC
Labels: bug
