### ISSUE TITLE
bluetooth_proxy less reliable than ble_monitor.parse_data

### ISSUE THREAD

**Issue by chatziko** [custom-components/ble_monitor#1035] opened 2022-10-07 09:34 UTC
Hello, for some time I was using ble_monitor with `ble_monitor.parse_data` to proxy data from a Xiami LYWSD03MMC via an esp32 board. It was pretty stable, getting one reading every 1 minute with very rare misses.

After 2022.09 I thought to try the native BTHome integration, with `bluetooth_proxy`. The sensor and esp32 boards are in the exact same location, but the readings are much less reliable now. Sometimes it takes 15 minutes to get a new one.

Anyone else experiencing a similar issue? Anything I can try to fix it?

**Comment by marcelveldt** [comment] 2022-10-11 07:10
I can confirm this too and am working on a possible fix.
My current thinking is that the ESP just needs to handle too much data because every packet is forwarded.

PR in-progress with a possible fix:
https://github.com/esphome/esphome/pull/3868

**Comment by WormyOne** [comment] 2022-10-24 21:13
Yes, I can confirm this reliability issue as well.  Initial triggering is frequently delayed by 0.75 to 3 seconds on some PIR sensors.  I was considering moving back to ble_monitor but looks like I should just sit tight.

Thx

**Comment by marcelveldt** [comment] 2022-10-27 07:32
Please check again with the new HA 2022.11 release next week (or this week in beta) because @bdraco has done an amazing job optimizing every aspect and it should already be a lot faster and more reliable.

**Comment by WormyOne** [comment] 2022-11-01 18:55
I've stuck with builtin, looking forward to testing fix in release.  I'm hoping to see an immediate difference and will report back.

**Comment by WormyOne** [comment] 2022-11-03 19:02
Installed 2022.11 about 90mins ago, and have noticed a marked improvement in responsiveness.  Looks like we are good.  Thanks for your efforts @bdraco @marcelveldt

**Comment by chatziko** [comment] 2022-11-10 10:08
It's hard to say for sure since my setup has changed a bit since the issue was opened, but it seems like 2022.11 has not fixed the problem for me. I'll keep an eye on https://github.com/esphome/esphome/pull/3868 to see whether that helps.

**Comment by Ernst79** [comment] 2023-01-28 22:07
Closing this issue here, as it is not related to BLE monitor.

**Closed by Ernst79** 2023-01-28 22:07 UTC
