### ISSUE TITLE
Runtime error while sending scan request

### ISSUE THREAD

**Issue by buhho-crtl** [custom-components/ble_monitor#584] opened 2021-12-14 22:24 UTC
Hi, I've been having this problem for a while when I try to connect the xiaomi thermometer with the bluetooth. The error happens with Home assistent and I don't know why, could someone give me a clue as to what it could be?

Cheers

> ``

```
31m2021-12-14 22:18:24 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci1: Event loop stopped before Future completed.. Resetting Bluetooth adapter 00:1A:7D:DA:71:13 and trying again.[0m
[31m2021-12-14 22:18:24 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
File "/config/custom_components/ble_monitor/__init__.py", line 608, in run
self._event_loop.run_until_complete(
File "/usr/lib/python3.9/asyncio/base_events.py", line 640, in run_until_complete
raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/config/custom_components/ble_monitor/__init__.py", line 619, in run
reset_bluetooth(hci)
File "/config/custom_components/ble_monitor/bt_helpers.py", line 151, in reset_bluetooth
mac = hci_get_mac([hci])[0]
KeyError: 0[0m

```

`  `

**Comment by Ernst79** [comment] 2021-12-15 06:43
Duplicate of #295 . Could you please post your issue in #295, also check that topic for some possible solutions.

**Closed** 2021-12-15 06:43 UTC
