### ISSUE TITLE
Support Qingping/Cleargrass broadcast (not encrypted)

### ISSUE THREAD

**Issue by Kal42** [custom-components/ble_monitor#81] opened 2020-06-06 16:16 UTC
Mostly base from the work in https://github.com/1technophile/OpenMQTTGateway

As far as I know, the CGD1 braodcast all the data in unencrypted form. also this shoud also work for https://fr.aliexpress.com/item/33043333798.html

How to parse the value:

1. Start with 0xCD 0xFD (instead of 0x95 0xFE for xiaomi)
2. After 2 Bytes :  0x08 x0C for the CGD1, for the one with air pressure 0x08 0x09
3. 6 Bytes : Reversed MAC

And after it's list object until the end, 
Object is : 1Byte type, 1Byte length, length bytes 

I have found three object:
0x01, temperature and humidity, with length 0x04, it's the same as xiaomi 0x100d
0x02, battery,   with length 0x01, it's the same as xiomi 0x1004
0x07 air pressure.  with length 0x02, it's double (uint16 value / 100)

one exemple:
`
CD FD 08 0C BF 65 52 34 2D 58 01 04 F1 00 AD 01 02 01 25
`
There is 2 object: 
- one of type 0x01, with temperature 0x00F1/10°C and humidty 0x01AD/10%
- one of type 0x02, with battery 0x25%

**Comment by Magalex2x14** [comment] 2020-06-15 19:14
Yes, during the implementation of the CGD1 alarm clock #38 support, I saw unencrypted messages.
However, since the message format is different from the Mija standard, I did not support it as unnecessary.
I will not close this topic - in the future, I promise to think about expanding the parser code, but I think that it will not be soon since several more important tasks need to be solved...

**Comment by flouck** [comment] 2020-12-13 14:53
I would love this to be implemented

**Comment by Magalex2x14** [comment] 2020-12-13 15:11
In the future, it is planned to have several parsers for different protocols. Hands have not yet reached this point.
Therefore, we are not closing this issue.

**Comment by kleju00** [comment] 2021-01-16 21:56
I have Qingping Temp RH Barometer (CGP1W) 

![284f0a04-c3e8-4672-86a6-26a3e5b1b979](https://user-images.githubusercontent.com/50960830/104823909-ec975980-584d-11eb-84f1-0711e28c8d4e.jpg)

and Qingping Air Monitor Lite (CGDN1). 

![41V-c3WqeBL _SX342_](https://user-images.githubusercontent.com/50960830/104823921-0cc71880-584e-11eb-9d1e-e4d5ce0c2315.jpg)

If needed, I can provide the hcidump file.

**Comment by Ernst79** [comment] 2021-01-17 10:22
Yes, please provide the hcidumps. I’ve almost finished the ATC protocol, so I can look into this as well.

 @Kal42 can you also send an hcidump?

**Comment by kleju00** [comment] 2021-01-17 12:40
hcidump 
[dump.txt](https://github.com/custom-components/ble_monitor/files/5826070/dump.txt)

CGP1W

Temp - 19,0 C
RH - 52,5 %
Pressure - 98,44 kPa


CGDN1

PM2.5 - 28
PM10 - 33
CO2 - 678 ppm
Temp - 17,0 C
RH - 71%

**Comment by Ernst79** [comment] 2021-01-17 17:10
Thanks, I'll look into it a.s.a.p. could you add the MAC address to your post above? Makes it easier to recognize for me which is which sensor.

**Comment by kleju00** [comment] 2021-01-17 18:24
CGP1W
Name: Qingping Temp RH Barometer
Address: 58:2D:34:40:1C:6F

CGDN1
Name: Qingping Air Monitor Lite
Address: 04:CF:8C:28:A4:0C

**Comment by Ernst79** [comment] 2021-01-24 22:03
I looked into the data, the **CGP1W** looks ok, I can make sense of it. I will implement a parser for that. 

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HCI  Evt Len Sub Num Evt  Peer -------MAC-------   Len Len Type Val Len  AD         Frame Product Frame ------MAC--------   ------------------------PAYLOAD---------------------  RSSI  
type code    evt rep type addr                             flag         type  UUID   ctrl   ID    cnt                      Type  Len  Temp   Hum   Type  Len Airpr. Type Len Batt 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD  08 09               6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  72 26   02   01  57  D1 
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD  08 09               6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  72 26   02   01  57  C8 
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD  08 09               6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  73 26   02   01  57  C8 
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD  08 09               6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  73 26   02   01  57  D0 
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD  08 09               6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  73 26   02   01  57  D1
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD  08 09               6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  72 26   02   01  57  C8 
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD  08 09               6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  72 26   02   01  57  D0
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD  08 09               6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  72 26   02   01  57  D0
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD  08 09               6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  73 26   02   01  57  CB 
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD  08 09               6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  73 26   02   01  57  D1 
                                                                             CD FD  08 0C               BF 65 52 34 2D 58   01    04  F1 00  AD 01                   02   01  25  XX
```

The last line is the sensor from @Kal42 

**Converting hex to decimals**
01 Temp 00 BE --> 00BE --> 190 --> T/10 --> 19,0 C
01 RH - 0D 02 --> 020D --> 525 --> H/10 --> 52,5 %
07 Pressure - 73 26 --> 2673 --> 9843 --> P/100 --> 98,44 kPa
02 Battery - 57 --> 87%

Note: 
08 09 for CGP1W,
08 0C for CGD1 (without air pressure)

**Comment by Ernst79** [comment] 2021-01-24 22:11
The **CGDN1** is a bit different, I can't make much sense of it. It has two types of data, `CD FD` as above and `8F 03` Not sure if it is even a UUID.

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HCI  Evt Len Sub Num Evt  Peer -------MAC-------   Len Len Type Val Len  AD         Frame Product Frame ------MAC--------      RSSI  
type code    evt rep type addr                             flag         type  UUID   ctrl   ID    cnt                       
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD  08 0E               0A A4 28 8C CF 04      DA 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C 00      0A A4 28 8C CF 04   81 D7
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD  08 0E               0A A4 28 8C CF 04      DB 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C 00      0A A4 28 8C CF 04   81 DB 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C 00      0A A4 28 8C CF 04   81 DB 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD  08 0E               0A A4 28 8C CF 04      DB 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD  08 0E               0A A4 28 8C CF 04      DB 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD  08 0E               0A A4 28 8C CF 04      D9 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C 00      0A A4 28 8C CF 04   81 D9 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD  08 0E               0A A4 28 8C CF 04      D9 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD  08 0E               0A A4 28 8C CF 04      DA 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C 00      0A A4 28 8C CF 04   81 DA 
 04   3E 1B  02  01   00   00  0C A4 28 8C CF 04   0F  02   01  06  0B   16  CD FD  08 0E               0A A4 28 8C CF 04      D9 
 04   3E 1F  02  01   00   00  0C A4 28 8C CF 04   13  02   01  06  0F   FF  8F 03  0A 10 3D 0C 00      0A A4 28 8C CF 04   81 D8
```

**Converting hex to decimals**
I've tried to convert some of the numbers, but they do not match yours. 
The `CD CF` lines do not have any data, perhaps the `08 0E`
08 0E --> 0E08 --> 3592 (PM10?)

The other lines also don't seem to make much sense. 
8F --> 143 (Temp?)
03 8F --> 911 (?)
03 0A --> 0A03 --> 2563 (PM2.5)
0A 10 --> 100A --> 4106 (?)
3D 0C --> 0C3D --> 3133 (PM10) 

Your values
PM2.5 - 28
PM10 - 33
CO2 - 678 ppm
Temp - 17,0 C
RH - 71%

**Comment by Ernst79** [comment] 2021-01-26 20:12
Thanks, I’ll look into it soon.

**Comment by Ernst79** [comment] 2021-02-03 15:01
Just a quick update. I managed to parse the messages for CGP1W and CGD1. I want to finish these two types first, and see if we can add the others later. Result of the parser looks good. 

```
result:  {'rssi': -47, 'mac': '582D34401C6F', 'type': 'CGP1W', 'packet': 'no packed id', 'firmware': 'Qingping', 'data': True, 'temperature': 19.0, 'humidity': 52.5, 'pressure': 984.2, 'battery': 87
```

Notes: 
- pressure is in hPa in Home Assistant. 
- UUID 0xFDCD belongs to Qingping Technology (Beijing) Co., Ltd.

**Comment by Ernst79** [comment] 2021-02-03 21:11
1.0.1-beta has been released with experimental support for Qingping advertisments. I've added support for CGD1 and CGP1W in this first version. Could you please test it?

**Comment by Ernst79** [comment] 2021-02-04 10:48
@kleju00 

I am looking at the last dump, and I found another Qingping device in your data

```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
HCI  Evt Len Sub Num Evt  Peer -------MAC-------   Len Len Type Val Len  AD  Xiaomi Frame Product Frame ------MAC--------   ------------------------PAYLOAD---------------------      RSSI  
type code    evt rep type addr                             flag         type  UUID   ctrl   ID    cnt                      Type  Len  Temp   Hum   Type  Len Airpr. Type Len Batt 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 04   3E 28  02  01   00   00  6F 1C 40 34 2D 58   1C  02   01  06  18   16  CD FD         08 09        6F 1C 40 34 2D 58   01    04  BE 00  0D 02  07   02  72 26   02   01  57      D1
 04   3E 24  02  01   00   00  B2 44 10 34 2D 58   18  02   01  06  14   16  CD FD         08 07        B2 44 10 34 2D 58   01    04  CA 00  45                      02   02  01  38  AF
```

I found the second line in your data, which follows the Qingping format. 
Can you tell me which what kind of device (type) has the MAC address 58:2D:34:10:44:B2 ? This measurement is Temperature + Humidity + battery?.

**Comment by andrewjswan** [comment] 2021-02-04 17:49
By any chance you can not use this protocol to synchronize time, and respond to the alarm in the Qingping Bluetooth Alarm Clock (CGD1)?

**Comment by kleju00** [comment] 2021-02-04 20:33
> Can you tell me which what kind of device (type) has the MAC address 58:2D:34:10:44:B2 ? This measurement is Temperature + Humidity + battery?.

This is CGG1 sensor without Qingping logo. Version without encryption.

> 1.0.1-beta has been released with experimental support for Qingping advertisments. I've added support for CGD1 and CGP1W in this first version. Could you please test it?

I have installed the beta version, unfortunately the CGN1 sensor is not detected as any entity. I no longer have CGD1 sensors at home. I have no way to check them.

BTW, the file also contains information from the MHO-C401 sensor - e-ink screen, square shape, Bluetooth, Xiaomi Home application. MAC A4:C1:38:4C:F8:F9 
https://www.gearbest.com/home-gadgets/pp_009887935148.html

and

PTH-3M formaldehyde sensor together with temperature and humidity measurement. You can also add it Xiaomi Home over Bluetooth.
https://www.aliexpress.com/item/1005001453182924.html

**Comment by Ernst79** [comment] 2021-02-04 21:54
> I have installed the beta version, unfortunately the CGN1 sensor is not detected as any entity.

It's correct that **CGDN1** is not detected. I have only added **CGP1W** and **CGD1** in this first release (I know, the names looks almost the same). 
@kleju Can you confirm that the **CGP1W** is working for you?

@andrewjswan @Kal42 Can you confirm that **CGD1** is working for you?

About the other two sensors
- MHO-C401 is already supported (it requires an encryption key)
- PTH-3M I look into this one as well.

**Comment by Ernst79** [comment] 2021-02-04 21:54
> By any chance you can not use this protocol to synchronize time, and respond to the alarm in the Qingping Bluetooth Alarm Clock (CGD1)?

@andrewjswan I think synchronizing time won't be possible, there is no time stamp in the BLE data. About responding to the alarm, that depends if the sensor sends a message or not, but lets find out. 
- First confirm that Temperature and Humidity is working. 
- Next, enable `report_unkown` and set debug logging to info level (see the faq)
- Next reload ble_monitor or restarting HA
- Now set the alarm, and watch the log if you see an REPORT UNKNOWN message
- When the alarm goes of, watch again in the log if you see a message.

**Comment by andrewjswan** [comment] 2021-02-05 14:46
> Can you confirm that **CGD1** is working for you?

I had it working before ...

**Comment by andrewjswan** [comment] 2021-02-05 14:47
> I think synchronizing time won't be possible

https://github.com/esphome/feature-requests/issues/643

**Comment by Ernst79** [comment] 2021-02-05 18:31
> I had it working before ...

Do you mean it worked, and now it doesn't anymore?

**Comment by andrewjswan** [comment] 2021-02-05 18:38
Now I don't know, i now on release branch...

пт, 5 февр. 2021 г., 20:31 Ernst Klamer <notifications@github.com>:

**Comment by Ernst79** [comment] 2021-02-05 19:48
@kleju00 I've created another issue for the PTH-3M sensor, as this isn't a Qingping sensor.

**Comment by Ernst79** [comment] 2021-02-07 09:47
- [ ] @kleju Can you confirm that the CGP1W is working for you with 1.0.1-beta?
- [ ] @Kal42 Can you confirm that CGD1 is working for you with 1.0.1-beta?

**Comment by kleju00** [comment] 2021-02-07 11:53
I do not have a CGP1W sensor at home. Maybe I'll have it on Tuesday.

**Comment by Ernst79** [comment] 2021-02-07 13:13
Ok, I thought you had one, as you posted the hcidump in the post 21 days ago.

**Comment by kleju00** [comment] 2021-02-08 15:54
The CGP1W sensor readings look good. Only the battery reading looks too low - see photo.

![Screenshot_2021-02-08-16-14-33-860_io homeassistant companion android](https://user-images.githubusercontent.com/50960830/107243955-cf5d4180-6a2d-11eb-969b-887161223221.jpg)
![Screenshot_2021-02-08-16-15-56-103_io homeassistant companion android](https://user-images.githubusercontent.com/50960830/107244001-d71ce600-6a2d-11eb-815d-5a71bb549e3d.jpg)
![Screenshot_2021-02-08-16-54-07-062_com google android apps photos](https://user-images.githubusercontent.com/50960830/107244488-59a5a580-6a2e-11eb-89ed-fc65d3567d0c.jpg)

**Comment by Ernst79** [comment] 2021-02-08 16:40
If you have set the encryption key, it will use both advertisement types. The Xiaomi (MiBeacon) just indicates which one came first. If you remove the encryption key, it will probably show Qingping as the firmware (oprogramowanie), after a restart.

I'm not sure why the battery is wrong. Do these sensors have an app where you can check it. In your previous log file, it looked pretty constant with an value of 57 (hex), which is 87% in decimals, which seems right.

**Comment by kleju00** [comment] 2021-02-08 17:32
The CGG1 sensor looks fine.
![Screenshot_2021-02-08-18-24-35-459_io homeassistant companion android](https://user-images.githubusercontent.com/50960830/107257611-2289c100-6a3b-11eb-9172-98bb47b3fa2f.jpg)

There is only a graphical battery indicator in the CGP1W sensor application.

![Screenshot_2021-02-08-18-27-31-676_com cleargrass app iot](https://user-images.githubusercontent.com/50960830/107258119-b9567d80-6a3b-11eb-908f-03de6d25b4e0.jpg)

The hcidump file in the PTH-3M thread contains the current data from this sensor.

**Comment by Ernst79** [comment] 2021-02-08 18:52
Strange. It's dropping quite fast, I agree that it might be something else than battery. 

One way to find out is to replace the battery (temporary). Do you have the possibility to replace the battery with a fresh one, just to check if it affects this measurement?

**Comment by kleju00** [comment] 2021-02-08 20:07
This sensor has a built-in 18650 cell. This is the problem because the rated voltage is 3.6V, not 3V. The charged cell is about 4.2V.

**Comment by Ernst79** [comment] 2021-02-09 07:24
I propose we release it first and have a look if other people also report strange battery behavior. The problem is that the other two sensors use the same "type code" for the battery.

**Comment by andrewjswan** [comment] 2021-02-10 08:37
> I think synchronizing time won't be possible, there is no time stamp in the BLE data. About responding to the alarm, that depends if the sensor sends a message or not, but lets find out.
> 
> * First confirm that Temperature and Humidity is working.
> * Next, enable `report_unkown` and set debug logging to info level (see the faq)
> * Next reload ble_monitor or restarting HA
> * Now set the alarm, and watch the log if you see an REPORT UNKNOWN message
> * When the alarm goes of, watch again in the log if you see a message.

I will try to do it with the alarm clock, and at the same time I will look at packages for Yeelight Wireless Switch S1 - YLAI003, I can also play with Xiaomi Smart Cube - XMMFo1JQD (but the protocol on it is already in the network - https://medium.com/@juananclaramunt/xiaomi-mi-smart-rubik-cube-ff5a22549f90 ).

**Comment by Ernst79** [comment] 2021-02-10 08:51
1.0.2 final has been released with support for CGG1, CGD1 and CGP1W. 

 CGDN1 is not added yet, this one needs further investigation.

**Closed** 2021-02-10 15:11 UTC
