### ISSUE TITLE
Setting "Generate battery entities" does not work

### ISSUE THREAD

**Issue by stefangries** [custom-components/ble_monitor#349] opened 2021-05-16 09:50 UTC
I have the "Generate battery entities" disabled:
![image](https://user-images.githubusercontent.com/10342151/118392929-6ee92c00-b63c-11eb-908f-2efad17b66dd.png)

When activating it and saving it, I get an error:
![image](https://user-images.githubusercontent.com/10342151/118392946-8de7be00-b63c-11eb-9ba7-6e93041f08d6.png)

Console output:
```
2021-05-16 11:43:21 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 213, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_configure
    user_input = cur_step["data_schema"](user_input)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 741, in __call__
    'value must be one of {}'.format(sorted(self.container)))
TypeError: '<' not supported between instances of 'bool' and 'str'
```

**Comment by Ernst79** [comment] 2021-05-16 10:53
Ill look into it. When you select e.g. Use median, do you get the same error?

**Comment by stefangries** [comment] 2021-05-16 11:47
Yes, same error.
Using Version 1.9.2.

**Comment by Ernst79** [comment] 2021-05-17 09:00
I think you need to select something (False) in the `Report Unknown` option. It is now empty, which isn't probably allowed.

**Comment by stefangries** [comment] 2021-05-17 09:05
Thanks, this solved the problem.

report_unknown is described as optional in the documentation. Therefore, either the documentation should be changed or omitting this option should not lead to errors.

https://github.com/custom-components/ble_monitor#report_unknown

**Comment by Ernst79** [comment] 2021-05-17 09:42
Yes, I understand, but this is more an issue with the configuration in the User Interface (UI). It should be filled in automatically with the default value (which is False), normally you should not see an empty field. When configuring it in YAML, you can leave it away, so in fact it is optional.

Not sure why it was empty in your case. Did you move from YAML configuration to configuration in the UI recently?

**Comment by stefangries** [comment] 2021-05-17 09:44
I did that when the UI configuration was introduced, so some time ago.

**Comment by Ernst79** [comment] 2021-05-17 10:13
Couldn't reproduce it (tried new (minimal) configuration in Yaml, then moved to UI mode. After that, when I open the options menu, report_unknown is filled in with False. 

I'm closing the issue for now. Will keep an eye on new issues, if more people are facing the same, might be related to the change in this option, (True isn't allowed anymore)

**Closed by Ernst79** 2021-05-17 10:13 UTC
