### ISSUE TITLE
module 'socket' has no attribute 'AF_BLUETOOTH'

### ISSUE THREAD

**Issue by Worrah** [custom-components/ble_monitor#171] opened 2020-11-25 22:27 UTC
Hello. Im trying to run this on Windows and getting an error `module 'socket' has no attribute 'AF_BLUETOOTH' `
What can i do? Could you maybe change to pybluez?

**Comment by Ernst79** [comment] 2020-11-26 06:33
Your python is compiled without Bluetooth support. You will need to compile python with Bluetooth. See [this solution](https://github.com/custom-components/ble_monitor/issues/125#issuecomment-713355926) for Linux. You will need to do something similar on Windows.

**Comment by Magalex2x14** [comment] 2020-11-26 10:27
I'm not sure if the aioblescan library will work at all on Windows...

**Comment by Worrah** [comment] 2020-11-26 10:45
> Your python is compiled without Bluetooth support. You will need to compile python with Bluetooth. See [this solution](https://github.com/custom-components/ble_monitor/issues/125#issuecomment-713355926) for Linux. You will need to do something similar on Windows.

problem is, Bluetooth sockets are not available on Windows


> I'm not sure if the aioblescan library will work at all on Windows...

But looks like pybluez might work. Yet idk what to code to make it work.
https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level/commit/a10c8d32cfdd51af67c99733b87ff1c231d07bec#diff-d69b6a61122e915c310d910b09c2f2269b8650d78d1c5041261044304ab214e4
I found this replacements, but still have not enought knowledge to figure it out

**Comment by Ernst79** [comment] 2021-01-17 17:27
Closing this issue, as a duplicate of #215. Please continue this conversation there.

**Closed by Ernst79** 2021-01-17 17:27 UTC
