### ISSUE TITLE
[Bug]:  restore_state at device level it is not working

### ISSUE THREAD

**Issue by 50494554524F** [custom-components/ble_monitor#998] opened 2022-08-26 15:39 UTC
### What happened?

```
  ble_monitor:
    bt_auto_restart: true
    discovery: false
    decimals: 2
    devices:
      - name: 'Xiaomi - Window Sensor - Test'            
        mac: 'MAC'
        encryption_key: 'KEY'
        restore_state: true
```
the state is not preserved after restart and it remain on unavailable until an event occour...

ble_monitor: 9.1.1

thanks

### Sensor type

Xiaomi Window Sensor 2

**Comment by Ernst79** [comment] 2022-09-04 19:54
Duplicate of #793, please check the last post there and provide some info such that I can narrow the issue down. I'm closing this issue, to keep things together in one issue.

**Closed by Ernst79** 2022-09-04 19:54 UTC
Labels: bug
