### ISSUE TITLE
Bad Request in most recent version of HA

### ISSUE THREAD

**Issue by hurricup** [custom-components/ble_monitor#544] opened 2021-11-04 17:20 UTC
Installed by cloning master and copying dir with component.

Just trying to install component to the HA, and getting error: 

```
styles.ts:365 POST http://192.168.0.100:8123/api/config/config_entries/flow/f69d350f576342a093f2b97d9319165d 400 (Bad Request)
I @ styles.ts:365
(anonymous) @ styles.ts:365
callApi @ styles.ts:365
f @ search-input.ts:19
value @ step-flow-form.ts:69
handleEvent @ styles.ts:365
```

![image](https://user-images.githubusercontent.com/2811330/140387886-ee689e66-fe41-4571-b876-9696b3ec16c6.png)

## System Health

version | core-2021.11.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.9.16-jethubj80
arch | aarch64
timezone | Europe/Moscow

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

**Comment by Ernst79** [comment] 2021-11-04 17:58
Duplicate of #543

**Comment by Ernst79** [comment] 2021-11-04 19:02
I moved your post to #543, closing this one.

**Closed by Ernst79** 2021-11-04 19:02 UTC
