### ISSUE TITLE
vent loop stopped before Future completed.. Resetting Bluetooth adapter

### ISSUE THREAD

**Issue by huuub** [custom-components/ble_monitor#574] opened 2021-12-04 18:22 UTC
I have the docker container ghcr.io/linuxserver/homeassistant installed on a rpi4.
Installed this ble_monitor but I keep getting this error :

```
2021-12-04 17:13:41 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.. Resetting Bluetooth adapter DC:A6:32:01:EB:7A and trying again.
2021-12-04 17:13:41 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
File "/config/custom_components/ble_monitor/__init__.py", line 582, in run
self._event_loop.run_until_complete(
File "/usr/lib/python3.9/asyncio/base_events.py", line 640, in run_until_complete
raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/config/custom_components/ble_monitor/__init__.py", line 593, in run
reset_bluetooth(hci)
File "/config/custom_components/ble_monitor/bt_helpers.py", line 159, in reset_bluetooth
bluetoothctl_select(mac)
File "/config/custom_components/ble_monitor/bt_helpers.py", line 95, in bluetoothctl_select
command = subprocess.run(["bluetoothctl", "select", mac], stderr=subprocess.PIPE, check=True)
File "/usr/lib/python3.9/subprocess.py", line 505, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'bluetoothctl'
```

If I login to the container this command works:
hcitool lescan

For now I have only the RTCGQ02LM that I want to add. 
I got the secret key but I cant get to the point where to add it.

**Comment by EcherArt** [comment] 2021-12-04 21:49
Same

**Comment by Ernst79** [comment] 2021-12-04 22:17
Duplicate of #295 

can you run the bluetoothctl command yourself?

encryption key can be added by selecting the Mac of your device at the bottom of the options menu of ble monitor. Clicking on submit will open the options for a specific device.

**Comment by EcherArt** [comment] 2021-12-05 10:18
When I enter the device details including the BLE key, it returns to general settings withut selecting the device I have entered. Is that normal? Because it looks like hanges haven't been saved.

**Comment by Ernst79** [comment] 2021-12-05 10:36
Yes, that's OK. just click submit again and you will exit the menu. If you open it again afterwards, you should see your encryption key is stored.

**Comment by EcherArt** [comment] 2021-12-05 11:03
Okay, then could the error causing logs to appear (same as huub's) could be the reason the device does not appear on the "devices" tab? Blueman and bluetoothctl can detect the device but can't pair to it as they don't use the encryption key (or I don't know how to use it with blueman/bluetoothctl)

**Comment by Ernst79** [comment] 2021-12-05 16:03
Yes, if you have this error, the Bluetooth dongle isn’t working. Please discuss this error in #295, I’m closing this issue, to collect all info in #295. There are also some solutions in #295 , but they do not work for everybody

**Closed by Ernst79** 2021-12-05 16:03 UTC

**Comment by huuub** [comment] 2021-12-06 14:00
I dont think so. In the other one I dont see that last line :
FileNotFoundError: [Errno 2] No such file or directory: 'bluetoothctl'
I am also using the bluetooth adapther from the rpi4 itself.

**Comment by huuub** [comment] 2021-12-06 14:10
> bluetoothctl

Hmm no... In the container it is not found

**Comment by huuub** [comment] 2021-12-06 16:19
I dont like it that you close my issue because somebody else says he has the same issue while I think he doesn't and I dont have the time to react?

**Comment by Ernst79** [comment] 2021-12-06 16:24
@huuub Sorry, didn't close it because someone else has the same issue. I closed it as your issue (Event loop stopped ...) is already discussed in issue #295. To prevent several topics about he same error, I decided to close this issue.

**Comment by huuub** [comment] 2021-12-06 16:25
I dont see anywhere in that treat the last error : 
FileNotFoundError: [Errno 2] No such file or directory: 'bluetoothctl'
