### ISSUE TITLE
Non-root container issue - runtime error

### ISSUE THREAD

**Issue by thi-baut** [custom-components/ble_monitor#558] opened 2021-11-13 20:33 UTC
Hi, 

I am running my HA docker container with a "low" privileged user (non root), the container is still running in host network mode.

When HA is booting I can see in the logs 

` HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed. `

My low privileged docker user is part of the "bluetooth" Ubuntu group. 

I activated debug mode for the integration but can't find what's the problem, it must be a permission or a tool that my user can't run, in that case I would add it to my sudoer file but I don't know which one it its. When running the container in root everything works fine.

Any idea? Thanks!

```

2021-11-13 20:19:51 DEBUG (MainThread) [custom_components.ble_monitor] Initializing BLE Monitor entry (config entry): <homeassistant.config_entries.ConfigEntry object at 0x7f1337ea6670>
2021-11-13 20:19:51 DEBUG (MainThread) [custom_components.ble_monitor] async_setup_entry: domain {}
2021-11-13 20:19:51 DEBUG (MainThread) [custom_components.ble_monitor] async_setup_entry: {'bt_interface': ['00:1A:7D:DA:71:13'], 'period': 60, 'discovery': True, 'active_scan': False, 'decimals': 1, 'log_spikes': False, 'use_median': False, 'restore_state': False, 'report_unknown': False, 'devices': [{'mac': '58:2D:34:34:43:ED', 'name': '582D343443ED'}], 'is_flow': True, 'hci_interface': [0]}
2021-11-13 20:19:51 DEBUG (MainThread) [custom_components.ble_monitor] HCI interface is [0]
2021-11-13 20:19:51 DEBUG (MainThread) [custom_components.ble_monitor] Spawning HCIdump thread
2021-11-13 20:19:51 DEBUG (MainThread) [custom_components.ble_monitor] HCIdump thread: Init
2021-11-13 20:19:51 DEBUG (MainThread) [custom_components.ble_monitor] 0 encryptors mac:key pairs loaded
2021-11-13 20:19:51 DEBUG (MainThread) [custom_components.ble_monitor] sensor whitelist: []
2021-11-13 20:19:51 DEBUG (MainThread) [custom_components.ble_monitor] 0 sensor whitelist item(s) loaded
2021-11-13 20:19:51 DEBUG (MainThread) [custom_components.ble_monitor] 0 device tracker(s) being monitored
2021-11-13 20:19:51 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: Run
2021-11-13 20:19:51 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: connected to hci0
2021-11-13 20:19:52 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Starting binary sensor entry startup
2021-11-13 20:19:52 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] BLE binary sensors updater initialization
2021-11-13 20:19:52 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] BLE binary sensors updater initialized
2021-11-13 20:19:52 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Binary sensor entry setup finished
2021-11-13 20:19:52 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Binary entities updater loop started!
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] Starting device tracker entry startup
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] BLE device tracker updater initialization
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] BLE device tracker updater initialized
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] Device Tracker entry setup finished
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] Device tracker updater loop started!
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Starting measuring sensor entry startup
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.sensor] BLE sensors updater initialization
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.sensor] BLE sensors updater initialized
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Measuring sensor entry setup finished
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Entities updater loop started!
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Sensor device with mac address 58:2D:34:34:43:ED has the following settings. Name: 582D343443ED. Temperature unit: °C. Decimals: 1. Use Median: False. Restore state: False. Reset Timer: 35
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Sensor device with mac address 58:2D:34:34:43:ED has the following settings. Name: 582D343443ED. Temperature unit: °C. Decimals: 1. Use Median: False. Restore state: False. Reset Timer: 35
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Sensor device with mac address 58:2D:34:34:43:ED has the following settings. Name: 582D343443ED. Temperature unit: °C. Decimals: 1. Use Median: False. Restore state: False. Reset Timer: 35
2021-11-13 20:19:54 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Sensor device with mac address 58:2D:34:34:43:ED has the following settings. Name: 582D343443ED. Temperature unit: °C. Decimals: 1. Use Median: False. Restore state: False. Reset Timer: 35
2021-11-13 20:19:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] async_added_to_hass called for ble temperature 582D343443ED
2021-11-13 20:19:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] async_added_to_hass called for ble humidity 582D343443ED
2021-11-13 20:19:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] async_added_to_hass called for ble battery 582D343443ED
2021-11-13 20:20:52 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 0 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
2021-11-13 20:20:55 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] 0 BLE ADV messages processed last 60 seconds for 0 device tracker device(s)
2021-11-13 20:20:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 1 measuring device(s)
2021-11-13 20:20:55 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.
2021-11-13 20:20:55 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: start main event_loop
2021-11-13 20:21:52 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 0 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
2021-11-13 20:21:55 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] 0 BLE ADV messages processed last 60 seconds for 0 device tracker device(s)
2021-11-13 20:21:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 1 measuring device(s)
2021-11-13 20:21:55 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: main event_loop stopped, finishing
2021-11-13 20:22:52 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 0 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
2021-11-13 20:22:55 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] 0 BLE ADV messages processed last 60 seconds for 0 device tracker device(s)
2021-11-13 20:22:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 1 measuring device(s)
2021-11-13 20:22:55 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed.
2021-11-13 20:22:55 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: Scanning will be restarted
2021-11-13 20:22:55 DEBUG (Thread-3) [custom_components.ble_monitor] 0 HCI events processed for previous period
2021-11-13 20:22:55 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: Run
2021-11-13 20:22:55 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: connected to hci0
2021-11-13 20:23:52 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 0 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
2021-11-13 20:23:55 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] 0 BLE ADV messages processed last 60 seconds for 0 device tracker device(s)
2021-11-13 20:23:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 1 measuring device(s)
2021-11-13 20:23:55 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.
2021-11-13 20:23:55 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: start main event_loop
2021-11-13 20:24:53 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 0 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
2021-11-13 20:24:56 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] 0 BLE ADV messages processed last 60 seconds for 0 device tracker device(s)
2021-11-13 20:24:56 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 1 measuring device(s)
2021-11-13 20:24:56 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: main event_loop stopped, finishing
2021-11-13 20:25:53 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 0 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
2021-11-13 20:25:56 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] 0 BLE ADV messages processed last 60 seconds for 0 device tracker device(s)
2021-11-13 20:25:56 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 1 measuring device(s)
2021-11-13 20:25:56 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while stop scan request on hci0: Event loop stopped before Future completed.
2021-11-13 20:25:56 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: Scanning will be restarted
2021-11-13 20:25:56 DEBUG (Thread-3) [custom_components.ble_monitor] 0 HCI events processed for previous period
2021-11-13 20:25:56 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: Run
2021-11-13 20:25:56 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: connected to hci0
2021-11-13 20:26:53 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 0 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
2021-11-13 20:26:56 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] 0 BLE ADV messages processed last 60 seconds for 0 device tracker device(s)
2021-11-13 20:26:56 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 1 measuring device(s)
2021-11-13 20:26:56 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.
2021-11-13 20:26:56 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: start main event_loop
2021-11-13 20:27:53 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] 0 MiBeacon BLE ADV messages processed for 0 binary sensor device(s) total. Priority queue = 0
2021-11-13 20:27:56 DEBUG (MainThread) [custom_components.ble_monitor.device_tracker] 0 BLE ADV messages processed last 60 seconds for 0 device tracker device(s)
2021-11-13 20:27:56 DEBUG (MainThread) [custom_components.ble_monitor.sensor] 0 BLE ADV messages processed for 1 measuring device(s)
2021-11-13 20:27:56 DEBUG (Thread-3) [custom_components.ble_monitor] HCIdump thread: main event_loop stopped, finishing
```

**Comment by Ernst79** [comment] 2021-11-14 10:06
Which version of BLE monitor do you have. Try 6.0.0-beta and enable the option.

![image](https://user-images.githubusercontent.com/24375847/141676568-14a34b47-5cea-4a0f-beec-29b8a482f389.png)

**Comment by thi-baut** [comment] 2021-11-14 16:53
Thanks for your response, I upgraded to 6.0.0-beta and ticked this box and the error is the same 

` HCIdump thread: Runtime error while sending scan request on hci0: Event loop stopped before Future completed.. Resetting Bluetooth adapter _(MAC redacted_) and trying again. `

I can see another new error which led me to believe that bluetoothctl is the problem. My user can run bluetoothctl and the select command:
![image](https://user-images.githubusercontent.com/1039268/141690370-3e061985-c1c8-4b21-a953-9059853f814c.png)


Details about the error in HA logs:

```

Uncaught thread exception

Traceback (most recent call last):
  File "/config/custom_components/ble_monitor/__init__.py", line 582, in run
    self._event_loop.run_until_complete(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 640, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 593, in run
    reset_bluetooth(hci)
  File "/config/custom_components/ble_monitor/bt_helpers.py", line 159, in reset_bluetooth
    bluetoothctl_select(mac)
  File "/config/custom_components/ble_monitor/bt_helpers.py", line 95, in bluetoothctl_select
    command = subprocess.run(["bluetoothctl", "select", mac], stderr=subprocess.PIPE, check=True)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bluetoothctl', 'select', '00:1A:7D:DA:71:13']' died with <Signals.SIGABRT: 6>.

```

**Comment by Ernst79** [comment] 2021-11-19 21:00
This issue is also discussed in #295, please also have a look there. There is no clear reason why this error occurs for some people. I'm not able to reproduce it. 

I also have no idea why it can't run `bluetoothctl select '00:1A:7D:DA:71:13'`, especially as you say that you can run it manually. Sorry.

**Comment by Ernst79** [comment] 2021-12-26 14:27
I'm closing this issue. Please continue to discuss this issue in #295, to keep all info at the same place. Note that the issue of BLE monitor not being able to run the bluetoothctl select command is an attempt to fix the initial `Event loop stopped before Future completed` issue, you should focus on solving that issue in the first place.

**Closed by Ernst79** 2021-12-26 14:27 UTC

**Comment by thi-baut** [comment] 2022-03-03 03:20
Hi all, I finally solved the issue by adding the 2 following capabilities to the HA docker container:
    cap_add:
      - NET_RAW
      - NET_ADMIN
      
Then after the container is started by running ` setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3.9\``

and restarting HA. Hope it helps someone...
