### ISSUE TITLE
Device tracker “bluetooth_tracker“ stop working

### ISSUE THREAD

**Issue by Vovoronale** [custom-components/ble_monitor#23] opened 2020-01-08 16:44 UTC
Device tracker “bluetooth_tracker“ stop working on raspberry pi 3+  when add platform mitemp_bt with error:
> Error looking up Bluetooth device
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/bluetooth/bluez.py", line 31, in discover_devices
>     lookup_class=lookup_class, device_id=device_id)
> _bluetooth.error: (4, 'Interrupted system call')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 140, in perform_bluetooth_update
>     devices = await hass.async_add_executor_job(discover_devices, device_id)
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 62, in discover_devices
>     device_id=device_id,
>   File "/usr/local/lib/python3.7/site-packages/bluetooth/bluez.py", line 34, in discover_devices
>     raise BluetoothError ("error communicating with local "
> bluetooth.btcommon.BluetoothError: error communicating with local bluetooth adapter

System | HassOS 3.7
arch | armv7l
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.5
timezone | Europe/Kiev
version | 0.103.5
virtualenv | false

Configuration.yaml
```
sensor:
  - platform: mitemp_bt
device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 10
    consider_home: 180
    new_device_defaults:
      track_new_devices: true
```

**Comment by Magalex2x14** [comment] 2020-01-11 03:26
Hi! Soon I will try to reproduce the problem, and we will think about the solution.

**Comment by Vovoronale** [comment] 2020-01-14 21:15
Maybe somehow connected to issue here https://github.com/home-assistant/home-assistant/issues/30147

**Comment by Magalex2x14** [comment] 2020-01-14 21:53
I could not reproduce your problem. BUT. My number of packets received from sensors decreases sharply (about 20 per minute becomes 1..3 per minute), and the tracker does not work, while the log is empty... Perhaps we are dealing with some kind of conflict. Perhaps the problem will be solved after closing of #9.

**Comment by Magalex2x14** [comment] 2020-01-22 19:48
I can not make the tracker work on my server ... However, I am waiting for feedback on the [0.5.0](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.5.0-alfa) version, since potentially new code will allow to catch events that lead to conflict (if this is the case).

**Comment by Magalex2x14** [comment] 2020-01-23 00:25
Observation of the `btmon` output showed that when the bluetooth_tracker starts, the number of hci-events on the bt-interface decreases sharply. mitemp_bt continues to receive advertisements, but with the `interval_seconds` interval, "BT LE traffic" slows down a lot by a dozen seconds. I tried to increase the `interval_seconds` to 60, and this led to the fact that the amount of data received by our component decreased slightly (compared to the tracker turned off).

 It turns out that the bluetooth tracker, as it were, "increases the load" on the bt-subsystem, which leads to a reduction in the amount of received measurements. The interval of 10 seconds is too short. If you nevertheless need just such an interval, then you need to increase the `period` in the mitemp_bt settings.

If you have time and desire, then try [0.5.1-alfa](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.5.1-alfa)

P.S. When I met HA, I also tried to work with bluetooth_tracker and bluetooth_LE_tracker, but refused them in favor of Wi-Fi (mikrotik + snmp tracker) due to their unstable operation and short range. I read that many solve the problem by installing some kind of third-party tracker with MQTT, and connect it to HA.

**Comment by Vovoronale** [comment] 2020-01-28 19:24
0.5.3 betta don’t work for me. Bluetooth_tracker works only when I turn off custom component. Error “… looking up Bluetooth device…“ do not appear any more.

**Comment by Magalex2x14** [comment] 2020-03-08 01:24
Obviously, we are dealing with a certain conflict, which is not yet possible to solve (unless we use separate BT-interfaces for the tracker and our component). Corresponding entry added to the [FAQ](https://github.com/custom-components/sensor.mitemp_bt/blob/master/faq.md#conflicts-with-other-components-using-the-same-bt-interface).

**Comment by Magalex2x14** [comment] 2020-11-21 14:41
I close because the possibility of a conflict is known and described in the documentation.

**Closed by Magalex2x14** 2020-11-21 14:41 UTC
