### ISSUE TITLE
Error on first use

### ISSUE THREAD

**Issue by freekeys** [custom-components/ble_monitor#388] opened 2021-06-03 22:52 UTC
Hi, I keep getting this error and cannot see any devices coming in. Any ideas? Thanks!

This error originated from a custom integration.

Logger: root
Source: custom_components/ble_monitor/__init__.py:524 
Integration: Passive BLE monitor (documentation, issues) 
First occurred: 23:31:08 (10 occurrences) 
Last logged: 23:49:10

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ble_monitor/__init__.py", line 524, in run
    self._event_loop.run_until_complete(btctrl[hci].send_scan_request(self._active))
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/aioblescan/aioblescan.py", line 1803, in send_scan_request
    if self._use_ext_scan():
  File "/usr/local/lib/python3.8/site-packages/aioblescan/aioblescan.py", line 1788, in _use_ext_scan
    return (self._supported_commands[37] & 0x60) == 0x60
TypeError: 'NoneType' object is not subscriptable

**Comment by Ernst79** [comment] 2021-06-04 07:07
hmm, this is the first time I've seen this error. It is an error from the [aioblescan pypi package](https://github.com/frawau/aioblescan/blob/84ef42a620cef1033884766430030686d0533d7c/aioblescan/aioblescan.py#L1784), but it is in a part of the code we have added ourselves. 

What kind of bluetooth dongle and system do you have. Do you have an Intel NUC?

**Comment by freekeys** [comment] 2021-06-04 08:22
I'm running HassOS on a Raspberry Pi 4. I haven't specifically turned Bluetooth on as I'm not using it for any other components - do I need to?

**Comment by freekeys** [comment] 2021-06-04 08:24
I've realised I need an encryption key and haven't defined one - could this be the problem?

**Comment by Ernst79** [comment] 2021-06-04 09:48
No, that is not related. It fails in setting up the communication with the bluetooth radio of your Pi. I will setup HassOs this weekend to check if I can reproduce this. 

Can you try to see if this built in component works?

https://www.home-assistant.io/integrations/bluetooth_le_tracker/

**Comment by Ernst79** [comment] 2021-06-04 12:19
Tried it on a clean install (RPi 3b+), but I can't reproduce it. 

![image](https://user-images.githubusercontent.com/24375847/120799766-71ee8280-c53f-11eb-9279-223722d71b22.png)

I think the first thing to check is to see if Bluetooth works with other standard HA Bluetooth components, like the one I mention above.

**Comment by freekeys** [comment] 2021-06-04 19:51
Tried installing bluetooth_le_tracker and interestingly I'm getting the error below - no more context though.. 

Logger: homeassistant.components.device_tracker
Source: components/device_tracker/legacy.py:260 
Integration: Device Tracker (documentation, issues)
First occurred: 20:39:10 (1 occurrences) 
Last logged: 20:39:10

Error setting up platform legacy bluetooth_le_tracker

**Comment by Ernst79** [comment] 2021-06-04 21:37
Look s like something is wrong with the Bluetooth on your system, but I’m not sure what. Normally it works out of the box on HassOs. I have to think what could be wrong.

**Comment by freekeys** [comment] 2021-06-04 23:04
Thanks so much!

**Comment by Ernst79** [comment] 2021-06-06 15:10
I can not really think of the cause of this issue. I suspect some serious issue with your bluetooth radio, but on Home Assistant OS it is quite difficult to investigate, as you don't have root access via SSH. What worries my is that even the build in components with Bluetooth don't work. 

Can you try one more time by setting up the mitemp_bt component. https://www.home-assistant.io/integrations/mitemp_bt/

**Comment by freekeys** [comment] 2021-06-06 22:21
Really appreciate your help with this. I get this error with mitemp_bt:

Logger: homeassistant.helpers.entity
Source: components/mitemp_bt/sensor.py:157 
First occurred: 23:09:38 (1 occurrences) 
Last logged: 23:09:38

Update for sensor.mitemp_bt_temperature fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/mitemp_bt/sensor.py", line 157, in update
    data = self.poller.parameter_value(self.parameter)
  File "/usr/local/lib/python3.8/site-packages/mitemp_bt/mitemp_bt_poller.py", line 126, in parameter_value
    self.fill_cache()
  File "/usr/local/lib/python3.8/site-packages/mitemp_bt/mitemp_bt_poller.py", line 59, in fill_cache
    self.firmware_version()
  File "/usr/local/lib/python3.8/site-packages/mitemp_bt/mitemp_bt_poller.py", line 106, in firmware_version
    self.battery = int(ord(res_battery))
TypeError: ord() expected a character, but string of length 15 found

**Comment by freekeys** [comment] 2021-06-06 22:21
And also:

Logger: homeassistant.components.mitemp_bt.sensor
Source: components/mitemp_bt/sensor.py:162 
Integration: mitemp_bt (documentation, issues) 
First occurred: 23:09:54 (21 occurrences) 
Last logged: 23:19:54

Polling error

**Comment by freekeys** [comment] 2021-06-06 22:22
But to be fair it's the v2 of the Mijia sensor so not sure it would work with this integration so guess it would throw an error anyway?

**Comment by Ernst79** [comment] 2021-06-10 06:37
Sorry I didn't got back to you sooner. 

V2 version of the sensor should not be the issue. 

In Mitemp_bt, you have a similar error.

```
TypeError: ord() expected a character, but string of length 15 found
```

Your Home Assistant is both in Mitemp_bt and in BLE monitor getting completely wrong data, it seems. Even before it is even starting to look at the data. If you really want to dig into the issue, I can try to help you with a custom version of BLE monitor, to find the cause of the issue, but I suspect some issue that is possibly hardware related (its a feeling). 

Other options to try first are a full restart of the HA system (not only HA). Another option would be using a bluetooth dongle. 

Let me know if you want to dig into the issue, I will then create a special version where we can do some debugging.

**Comment by Ernst79** [comment] 2021-06-24 20:59
Any update or can we close this issue?

**Comment by freekeys** [comment] 2021-07-03 00:33
Thanks for your help! Think it must be a hardware issue - I gave up and went via a ESP32 instead 😊

**Closed** 2021-07-03 06:26 UTC
Labels: bug
