### ISSUE TITLE
[Bug]: Error adding entities for domain sensor with platform ble_monitor

### ISSUE THREAD

**Issue by ilsalgo** [custom-components/ble_monitor#857] opened 2022-05-06 13:44 UTC
### What happened?

Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:530
Integration: Sensore (documentation, issues)
First occurred: 15:21:58 (5 occurrences)
Last logged: 15:21:58

Error adding entities for domain sensor with platform ble_monitor
Error while setting up ble_monitor platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 344, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 625, in async_update_entity
    return self._async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 530, in _async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

### Sensor type

ble_monitor

**Comment by Ernst79** [comment] 2022-05-06 15:45
Can you provide some more info? Is this a new installation, or existing? Did it occur after a HA update?

**Comment by ilsalgo** [comment] 2022-05-06 15:48
@Ernst79 is an existing installation, I didn't see this error before today's update.

**Comment by Ernst79** [comment] 2022-05-06 15:50
I assume you mean the HA update to 2022.5.1? Didn’t see any error on my system so far. Can you tell me which sensors you have? Probably one of the entities is causing the issue.

**Comment by ilsalgo** [comment] 2022-05-06 15:59
@Ernst79 yes, sorry, 2022.5.1. I have 4 temperature and humidity sensors XMWSDJ04MMC and one LYWSDCGQ. The version of BLE monitor is 8.6.4

**Comment by Ernst79** [comment] 2022-05-06 18:16
Hmm, I can't reproduce it. If I copy some of the test BLE advertisements, the device is added normally. 

could you try to delete the devices from the BLE monitor options menu (Select the mac in the devices pull down menu, click submit, make a note of the encryption key, if used, select delete device. It will be automatically added afterwards. After closing the menu and after it has been re-added, you can enter your encryption key.

**Comment by Ernst79** [comment] 2022-05-06 18:19
What you can also try it to enable debug logging. When the error occurs, copy some lines from the HA log just before that, it might give me a clue which entity is causing issues.

**Comment by ilsalgo** [comment] 2022-05-06 19:58
@Ernst79 
![Screenshot_20220506_214828](https://user-images.githubusercontent.com/32997790/167208509-5dee5600-56aa-4ab4-943c-6fcb90abcdf7.jpg)

**Comment by Ernst79** [comment] 2022-05-06 20:16
Please click on the full log to get three debug log. It’s a button somewhere at the bottom to show the full log

**Comment by ilsalgo** [comment] 2022-05-06 20:35
@Ernst79 
![Uploading Screenshot_20220506_223424.jpg…]()

**Comment by Ernst79** [comment] 2022-05-07 06:34
I think something when wrong with uploading the image? You can also copy the text directly here

**Comment by ilsalgo** [comment] 2022-05-07 07:36
@Ernst79 
![Screenshot_20220506_223424](https://user-images.githubusercontent.com/32997790/167244088-c5a8525b-a236-43c9-b3e2-89a6aa3f7182.jpg)

**Comment by Ernst79** [comment] 2022-05-07 13:32
hmmm, not very helpful messages. I also checked the changes in HA, but can't find anything that could cause this issue. I also haven't received any other similar issues, so my guess is that there is something wrong with your installation. Could you

1. Check the file /config/custom_compomentens/ble_monitor/manifest.json and check which version you have over there. 
2. If the version is the same as in HACS, try to reinstall ble_monitor. (remove - restart HA - add - restart HA).

**Closed** 2022-07-19 13:30 UTC
Labels: bug
