### ISSUE TITLE
LYWSDCGQ no data since update

### ISSUE THREAD

**Issue by Toukite** [custom-components/ble_monitor#375] opened 2021-05-29 09:27 UTC
Hello,
There was several updates in the past few days, and now I notice that I don't have anymore data coming from my temp sensors.
There are no errors in the logs, but i noticed that the log saying which is the bt interface used (at startup) is not showing up anymore
Tried rebooting, restarting, reloading .... nothing works

**Comment by Ernst79** [comment] 2021-05-29 09:44
Probably a duplicate of #372, are you using `discovery: False`?

**Comment by Ernst79** [comment] 2021-05-29 09:53
@Toukite, I'm closing this issue, I'll continue in #372. I can confirm the issue, will fix it a.s.a.p.

**Closed by Ernst79** 2021-05-29 09:53 UTC

**Comment by Toukite** [comment] 2021-05-29 09:58
Ok thanks
Yes I have discovery and active scan set to false a'd yaml config

**Comment by Ernst79** [comment] 2021-05-29 10:00
Set discovery to True temporary, till it is fixed.
