### ISSUE TITLE
[Bug]: WARNING no BT LE capabilities and will be ignored.

### ISSUE THREAD

**Issue by borpin** [custom-components/ble_monitor#810] opened 2022-03-31 09:20 UTC
### What happened?

I am suddenly getting this error - V 8.4.0
```
WARNING (MainThread) [custom_components.ble_monitor.bt_helpers] hci0 (00:0A:3A:67:D3:1C) have no BT LE capabilities and will be ignored.
```
I have 2 identical BLE dongles, one is fine the other complains!

May be linked to the latest HA OS update (this is running on a Blue).

Only offering one interface in options

![image](https://user-images.githubusercontent.com/1322749/161020790-296ee1ec-e1d7-453a-b31c-3130a09e7756.png)

Unplugging the working BLE dongle (`hci1`), results in this
```
022-03-31 10:14:20 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: OS error (hci1): [Errno 19] error while attempting to bind on interface 1: No such device
2022-03-31 10:14:20 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Trying to power cycle Bluetooth adapter hci1 00:1A:7D:DA:71:13, will try to use it next scan period.
2022-03-31 10:14:20 ERROR (Thread-3) [custom_components.ble_monitor.bt_helpers] RF kill switch check failed - no data for hci1. Available data: {'hci0': {'idx': 0, 'type': 'bluetooth', 'soft': False, 'hard': False}}
2022-03-31 10:14:20 WARNING (Thread-3) [custom_components.ble_monitor.bt_helpers] hci0 (00:0A:3A:67:D3:1C) have no BT LE capabilities and will be ignored.
2022-03-31 10:14:20 ERROR (Thread-3) [custom_components.ble_monitor.bt_helpers] hci1 seems not to exist (anymore), check BT interface mac address in your settings. Available adapters: {} 
```
Unplugging the other (it is linked via RJ45/USB extenders) has no log entries as a result in homeassistant log, but it is noted in HA OS logs (first is `hci1`, second is `hci0`)

```
[ 8549.134958] usb 1-1.1.3: USB disconnect, device number 9
[ 8551.917493] usb 1-1.1.3: new full-speed USB device number 10 using xhci-hcd
[ 8613.133750] usb 1-1.3: USB disconnect, device number 4
[ 8615.170548] usb 1-1.3: new full-speed USB device number 11 using xhci-hcd
```

**Comment by Ernst79** [comment] 2022-03-31 14:14
Most of the times a full restart of the system helps, especially after an OS update. Do not only restart HA, but the entire system

**Comment by borpin** [comment] 2022-03-31 20:39
Yes, tried a cold boot. No change.

Most odd :(

**Comment by Ernst79** [comment] 2022-03-31 20:41
@Magalex2x14 do you have an idea?

**Comment by kksligh** [comment] 2022-04-01 13:50
same issue here

**Comment by Magalex2x14** [comment] 2022-04-01 14:33
@Ernst79 for experiment or as a temporary solution, you can comment out these lines in bthelpers для отключения проверки , and publish the beta:
```python
            bt_le = bool(
                hci_info.cmd_response_frame.supported_settings & 0b000000001000000000
            )
            if bt_le is not True:
                _LOGGER.warning(
                    "hci%i (%s) have no BT LE capabilities and will be ignored.",
                    idx,
                    hci_info.cmd_response_frame.address,
                )
                continue
```

**Comment by kksligh** [comment] 2022-04-02 02:42
I've tried everything and can't get any device to work. All entities show unknown. I know how to pull debug logs but I'm not sure how or what you're needing in reference to root access on the operating system. Please give me some direction and I'll do it...I think this is clearly linked to the latest OS update. This started immediately after I updated. It's very odd and essentially makes ble completely broken for me.

**Comment by Magalex2x14** [comment] 2022-04-02 02:57
[Root access to the host OS.](https://developers.home-assistant.io/docs/operating-system/debugging/#ssh-access-to-the-host)

If this seems difficult for you, then do not suffer. Let's first look at the debug log. We need to make sure that the system is actually reporting the lack of LE capabilities, and that ble_monitor understands this correctly. Meanwhile, I'll try to see what changes in the operating system could cause the problem...

**Comment by Magalex2x14** [comment] 2022-04-02 04:20
Also, I tried to reproduce the issue - updated the test system (official HA OS OVA image, Asus USB-BT4.0 dongle, Broadcom), but everything works without problems. I recently switched my main system with two adapters to Docker - the last update of the official image also did not bring any problems...

Perhaps the problem is related to specific adapters. What BT adapters do you use?

**Comment by kksligh** [comment] 2022-04-02 11:22
I unistalled everthing and changed the USB port of the adapter, and finally it came back. I'm good to go!

**Comment by Ernst79** [comment] 2022-04-06 16:06
@borpin Did you had a look at the questions from @Magalex2x14 ?

> @borpin @kksligh do you have root access to the host operating system?
If yes, then we need the output of the command hciconfig hci0 features and hciconfig hci1 features.
In addition, you need to [enable debug logging](https://custom-components.github.io/ble_monitor/faq#debug) and restart HA - there will be extended information about adapters immediately after the integration start.

**Comment by borpin** [comment] 2022-05-15 12:48
Hi, this is a Blue and I have never managed to get the Host OS to load the SSH Key, so no, sorry.

Update to latest version of OS and this integration. Now only ever see one BT dongle.

```
22-05-15 13:30:00 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/bus/usb/001/044 - None

22-05-15 13:31:17 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/bus/usb/001/045 - None
```
Unplug dongles and plug them back in. Related HA logs.
```
2022-05-15 13:30:39 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: OS error (hci1): [Errno 19] error while attempting to bind on interface 1: No such device
2022-05-15 13:30:39 ERROR (Thread-3) [custom_components.ble_monitor] HCIdump thread: Trying to power cycle Bluetooth adapter hci1 00:1A:7D:DA:71:13, will try to use it next scan period.
2022-05-15 13:30:39 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] Power cycling Bluetooth adapter hci1
2022-05-15 13:30:39 ERROR (Thread-3) [custom_components.ble_monitor.bt_helpers] RF kill switch check failed - no data for hci1. Available data: {'hci0': {'idx': 37, 'type': 'bluetooth', 'soft': False, 'hard': False}}
2022-05-15 13:30:39 DEBUG (Thread-3) [custom_components.ble_monitor.bt_helpers] Response(header=<event_code=CommandCompleteEvent, controller_idx=0, param_len=283>, event_frame=<command_opcode=ReadControllerInformation, status=Success>, cmd_response_frame=<address=00:1A:7D:DA:71:13, bluetooth_version=6, manufacturer=10, supported_settings=114431, current_settings={Powered: True, Connectable: False, FastConnectable: False, Discoverable: False, Bondable: False, LinkLevelSecurity: False, SecureSimplePairing: True, BREDR: True, HighSpeed: False, LowEnergy: True, Advertising: False, SecureConnections: True, DebugKeys: False, Privacy: False, ControllerConfiguration: False, StaticAddress: False, PHYConfiguration: False, WidebandSpeech: False}, class_of_device=0, name=b'homeassistant', short_name=0>)
2022-05-15 13:30:39 ERROR (Thread-3) [custom_components.ble_monitor.bt_helpers] hci1 seems not to exist (anymore), check BT interface mac address in your settings. Available adapters: {0: '00:1A:7D:DA:71:13'} 
```
Info from system menu on these USB devices
```
BUSNUM: '001'
DEVNAME: /dev/bus/usb/001/045
DEVNUM: '045'
DEVPATH: /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.3
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_MODEL: Belkin_Bluetooth_Device
ID_MODEL_ENC: Belkin\x20Bluetooth\x20Device
ID_MODEL_ID: 200a
ID_PATH: platform-xhci-hcd.1.auto-usb-0:1.3
ID_PATH_TAG: platform-xhci-hcd_1_auto-usb-0_1_3
ID_REVISION: '0001'
ID_SERIAL: Broadcom_Belkin_Bluetooth_Device_000A3A67D31C
ID_SERIAL_SHORT: 000A3A67D31C
ID_USB_INTERFACES: ':e00101:ffffff:'
ID_VENDOR: Broadcom
ID_VENDOR_ENC: Broadcom
ID_VENDOR_ID: 0a5c
MAJOR: '189'
MINOR: '44'
PRODUCT: a5c/200a/1
SUBSYSTEM: usb
TYPE: 224/1/1
USEC_INITIALIZED: '2962507371397'


BUSNUM: '001'
DEVNAME: /dev/bus/usb/001/044
DEVNUM: '044'
DEVPATH: >-
  /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.1/1-1.1.3
DEVTYPE: usb_device
DRIVER: usb
ID_BUS: usb
ID_MODEL: CSR8510_A10
ID_MODEL_ENC: CSR8510\x20A10
ID_MODEL_ID: '0001'
ID_PATH: platform-xhci-hcd.1.auto-usb-0:1.1.3
ID_PATH_TAG: platform-xhci-hcd_1_auto-usb-0_1_1_3
ID_REVISION: '8891'
ID_SERIAL: 0a12_CSR8510_A10
ID_USB_INTERFACES: ':e00101:'
ID_VENDOR: 0a12
ID_VENDOR_ENC: 0a12
ID_VENDOR_ID: 0a12
MAJOR: '189'
MINOR: '43'
PRODUCT: a12/1/8891
SUBSYSTEM: usb
TYPE: 224/1/1
USEC_INITIALIZED: '2962430088283'
```
On the BLE Integration menu I see just the one BT interface
```
MAC address of the Bluetooth interface/adapter
00:1A:7D:DA:71:13 (hci1)
```

I could do with a second to increase BT coverage in my house.

**Comment by Ernst79** [comment] 2022-07-09 20:34
Did you ever solved this issue?

**Comment by borpin** [comment] 2022-07-11 15:08
No and I noticed the error the other day and though "I need to find time to look at this"!

**Comment by Ernst79** [comment] 2023-01-15 11:28
Closing this issue. If it is still relevant, feel free to reopen.

**Closed by Ernst79** 2023-01-15 11:28 UTC
Labels: bug
