### ISSUE TITLE
Support for Thermoplus / ThermoBeacon hydrometers

### ISSUE THREAD

**Issue by araines** [custom-components/ble_monitor#393] opened 2021-06-06 11:22 UTC
I built a BLE custom component for Thermoplus hydrometers a while ago, but having found this component which is much more feature rich, I think it makes sense to get the support in here instead of my limited implementation: https://github.com/araines/homeassistant-thermoplus-ble

In terms of how these work, the code above seems to mostly work, but here are some details:

The sensors appear to broadcast three different messages, one which identifies the sensor as a "ThermoBeacon", one which contains the temp, humidity & battery data, and another one which I have not determined the purpose of it.

As an example, here is one of my sensors:
```
# hcitool lescan
LE Scan ...
9B:B0:00:00:02:60 (unknown)
9B:B0:00:00:02:60 ThermoBeacon
```

Then from the HCI dump:
```
# cat dump.txt | grep '60 02 00 00 B0 9B'
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 28 0B 64 01 9E 03 9A
> 04 3E 2B 02 01 00 00 60 02 00 00 B0 9B 1F 02 01 06 03 02 F0
  FF 17 FF 11 00 00 00 60 02 00 00 B0 9B 95 01 1B 45 0D 00 11
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 30 0B 64 01 9E 03 9C
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 30 0B 64 01 9E 03 9D
> 04 3E 2B 02 01 00 00 60 02 00 00 B0 9B 1F 02 01 06 03 02 F0
  FF 17 FF 11 00 00 00 60 02 00 00 B0 9B 95 01 1B 45 0D 00 11
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 2D 0B 64 01 9E 03 9F
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 2D 0B 64 01 9E 03 A0
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 2D 0B 64 01 9E 03 A0
> 04 3E 2B 02 01 00 00 60 02 00 00 B0 9B 1F 02 01 06 03 02 F0
  FF 17 FF 11 00 00 00 60 02 00 00 B0 9B 95 01 1B 45 0D 00 11
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 2F 0B 64 01 9E 03 A2
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 2F 0B 64 01 9E 03 A3
> 04 3E 2B 02 01 00 00 60 02 00 00 B0 9B 1F 02 01 06 03 02 F0
  FF 17 FF 11 00 00 00 60 02 00 00 B0 9B 95 01 1B 45 0D 00 11
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 2F 0B 64 01 9E 03 A5
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 2F 0B 64 01 9E 03 A5
> 04 3E 2B 02 01 00 00 60 02 00 00 B0 9B 1F 02 01 06 03 02 F0
  FF 17 FF 11 00 00 00 60 02 00 00 B0 9B 95 01 1B 45 0D 00 11
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 31 0B 64 01 9E 03 A9
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 31 0B 64 01 9E 03 AB
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 2F 0B 64 01 9E 03 AB
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 2F 0B 64 01 9E 03 AC
> 04 3E 2B 02 01 00 00 60 02 00 00 B0 9B 1F 02 01 06 03 02 F0
  FF 17 FF 11 00 00 00 60 02 00 00 B0 9B 95 01 1B 45 0D 00 11
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 30 0B 64 01 9E 03 AE
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 30 0B 64 01 9E 03 AF
> 04 3E 2B 02 01 00 00 60 02 00 00 B0 9B 1F 02 01 06 03 02 F0
  FF 17 FF 11 00 00 00 60 02 00 00 B0 9B 95 01 1B 45 0D 00 11
> 04 3E 2B 02 01 00 00 60 02 00 00 B0 9B 1F 02 01 06 03 02 F0
  FF 17 FF 11 00 00 00 60 02 00 00 B0 9B 95 01 1B 45 0D 00 11
> 04 3E 29 02 01 00 00 60 02 00 00 B0 9B 1D 02 01 06 03 02 F0
  FF 15 FF 11 00 00 00 60 02 00 00 B0 9B 2F 0B 64 01 9E 03 B2
> 04 3E 2B 02 01 00 00 60 02 00 00 B0 9B 1F 02 01 06 03 02 F0
  FF 17 FF 11 00 00 00 60 02 00 00 B0 9B 95 01 1B 45 0D 00 11
```

Approximately at the time of the above dump the sensor read close to: 22.3C 57% humidity.

This test file shows basically how the decoding works: https://github.com/araines/homeassistant-thermoplus-ble/blob/master/test.py
Giving this output:
```
RAW1 (Med packet - 44 bytes)
('06:88:00:00:16:27',)
[{'data_type': b'\x01', 'length': 2, 'value': b'\x06'}, {'data_type': b'\x02', 'length': 3, 'value': b'\xf0\xff'}, {'data_type': b'\xff', 'length': 21, 'value': b"\x11\x00\x00\x00'\x16\x00\x00\x88\x06<\x0c\x8f\x01\xa1\x03\xb9\xd7\x03"}]
mac: 06:88:00:00:16:27
Payload: 3132 24.94 58.06 -56

RAW2 (Long packet - 46 bytes)
('06:88:00:00:16:27',)
[{'data_type': b'\x01', 'length': 2, 'value': b'\x06'}, {'data_type': b'\x02', 'length': 3, 'value': b'\xf0\xff'}, {'data_type': b'\xff', 'length': 23, 'value': b"\x11\x00\x00\x00'\x16\x00\x00\x88\x06\xfa\x01\x98\x17\x00\x00T\x01Ns\x02"}]

RAW3 (Short packet - 38 bytes)
('06:88:00:00:16:27',)
[{'data_type': b'\t', 'length': 13, 'value': b'ThermoBeacon'}, {'data_type': b'\x12', 'length': 5, 'value': b'\x18\x008\x01'}, {'data_type': b'\n', 'length': 2, 'value': b''}]
ThermoBeacon
```

Noting here that the medium length message has the payload:
```
3132 - Battery voltage in mV
24.94 - Temperature in C
58.06 - Humidity %
-56 - Signal strength (RSSI)
```

According to the reverse-engineered app code, the battery voltage is interpreted as such:
| Voltage | Level |
| --- | --- |
| >=3000 | 100% |
| >=2800 | 80% |
| >=2600 | 60% |
| >=2500 | 40% |
| >=2450 | 20% |
| <2450 | 0% |

The temperature and humidity values are the raw value divided by 16 to get the true values (details in the code).

For auto-discovery my implementation looks for sensors emitting the ThermoBeacon identifier, then remembers those MAC addresses.  Any subsequent messages emitted from those MAC addresses are analysed to find the correct (medium length) message and then decoded to get the associated data.

**Comment by Ernst79** [comment] 2021-06-06 11:50
Hi, It looks possible to implement support for this, I will take care of it. I have to add some other stuff first, but will get back to you a.s.a.p.

**Comment by araines** [comment] 2021-06-06 11:57
That's awesome, thanks.  Please let me know if there is anything I can help with.  I had a quick look at the code in this component, and I'd definitely need to spend quite some time getting myself up to speed with how it all works - but happy to do so if I can be helpful!

I should mention as well - I've got 7 of these sensors now so I can provide more dumps etc if that is helpful.

**Comment by Ernst79** [comment] 2021-06-06 13:47
When I have a first draft, I will create a beta for you to test.

**Comment by Ernst79** [comment] 2021-06-06 15:33
@araines, I think there is something with the HCI dump, all lines are 40 bytes, while the third byte shows different lengths. Could you check this?

**Comment by Ernst79** [comment] 2021-06-06 15:35
Nevermind, I found some examples in the code.

**Comment by Ernst79** [comment] 2021-06-06 17:59
I have the parser working, but I notice that there are three devices on your link. Are all three devices sending the same advertisements? Is there a way to see the difference, you think?

```
15ff11000000 271600008806 3c0c 8f01 a103 b9d70300 c8
```

If you look at this payload, I see

MAC reversed (byte 6 - 11):  `271600008806`
voltage: (byte 12 - 13): `3c0c`
temperature (byte 14 - 15): `8f01`
humidity (byte 16 - 17): `a103`
??? (byte 18 - 21): `b9d70300`
RSSI: (byte 22): `c8`

These byte 18-21, any idea what these are used for. Can it be an indication which device it is? Xiaomi and Qingping are using two bytes to define the device type. Is it possible for you to check?

**Comment by araines** [comment] 2021-06-06 19:51
Wow, I really wasn't expecting you to get on with that so fast!

In terms of the devices - I've actually only tested with the first one, but I've had people tell me the others worked without any further modification on my part.  Therefore I assume they are all functionally equivalent.

Bytes 18-21 represent the time since the sensor was activated in seconds (I think).  Basically it just increments over time.  Not much use.

**Comment by Ernst79** [comment] 2021-06-07 06:32
Not needed, thanks, I have all info I need. Beta will be released this evening, First I have to release a final with earlier changes.

**Comment by Ernst79** [comment] 2021-06-07 17:05
3.1.0-beta has been released, please give it a try and let me know if it all works. No need to set a MAC, it will auto-detect if discovery is set to True (default)

**Comment by ACrazyConcept** [comment] 2021-06-07 20:03
First of all thanks @araines for suggesting this addition/merge of efforts, it makes a lot of sense. And thanks @Ernst79 for a speedy update.

Second. I have just now updated to this beta. But I don't see any of the ThermoBeacons. I have a couple of the mini hygrometers and lanyard hygrometers.
Config:

```
ble_monitor:
  discovery: True
  active_scan: False
  report_unknown: False
  decimals: 2
  log_spikes: False
  use_median: False
  restore_state: True
  devices:
    - mac: 'XX:XX:XX:XX:XX:XX' # ThermoBeacon
```

**Comment by araines** [comment] 2021-06-07 20:08
I've just finished setting all seven of my sensors up and checking their values etc - everything looks as I would expect.  Auto-detect worked perfectly.  This implementation is _so much better_ than mine.  Being able to do everything via the UI is awesome, having devices and entities appear properly is awesome too.

Just to be clear about how I've tested this - I installed via HACS, restarted the server, then added the integration via the UI and it self-detected everything.  I didn't touch the YAML configuration side of things at all.

**Comment by Ernst79** [comment] 2021-06-07 20:15
@ACrazyConcept that is strange, as it is working for @araines. Are you sure you have the correct version? Did you restart after the update? Are there any errors in the log.

could you try report_unknown option,  try first with Thermoplus, if that doesn’t work, try with Other. Make sure you enable debug logging at info level, see the explanation how in the FAQ (how to request for a new sensor)

**Comment by araines** [comment] 2021-06-07 20:23
Just deleted the integration and reinstalled and it self-discovered all seven sensors again with active scan disabled this time - so it looks like it works either way for me.

**Comment by araines** [comment] 2021-06-07 20:32
@Ernst79 thank you so much for your hard work and also turning this around so quickly.  Happy to help debugging if there is anything I can do.

**Comment by ACrazyConcept** [comment] 2021-06-07 20:46
Still can't seem to get anything in the log either.

But I think they do show up in a hcidump (huge log) and I can see them with btmon. E.g.:

```
> HCI Event: LE Meta Event (0x3e) plen 41                                                       #236 [hci0] 3.778261
      LE Advertising Report (0x02)
        Num reports: 1
        Event type: Connectable undirected - ADV_IND (0x00)
        Address type: Public (0x00)
        Address: 70:F7:00:00:14:88 (OUI 70-F7-00)
        Data length: 29
        Flags: 0x06
          LE General Discoverable Mode
          BR/EDR Not Supported
        16-bit Service UUIDs (partial): 1 entry
          Unknown (0xfff0)
        Company: Mitel Semiconductor (16)
          Data: 000088140000f7709f0b7401d70281610400
        RSSI: -60 dBm (0xc4)
```

**Comment by Ernst79** [comment] 2021-06-07 21:26
Did you enable logging?

```
logger:
  default: warn
  logs:
    custom_components.ble_monitor: info
```

What kind of installation do you have, HassOs, HA supervised, venv?

**Comment by ACrazyConcept** [comment] 2021-06-07 22:15
Yes

```
logger:
  default: warning
  logs:
    custom_components.ble_monitor: info
```

```
ble_monitor:
  bt_interface: 
    - 'B8:27:EB:0C:E2:C7'
    - 'B8:27:EB:0C:E2:C8'
  discovery: True
  active_scan: False
  report_unknown: 'Other'
  decimals: 2
  log_spikes: False
  use_median: False
  restore_state: True
  devices:
```

Well this one is a Home Assistant Blue / Odroid N2+ but it's running Armbian and Home Assistant in docker (just upgraded from 2021.5.1 to 2021.6.2, but no difference).
I do have a buch of other sensors in ble_monitor on this box which are all working fine: MJYD02YL, SJWS01LM, CGG1, LYWSD03MMC, HHCCJCY01, GCLS002.

I could set up a RPi with a clean HA OS one of the coming days for testing.

**Comment by Ernst79** [comment] 2021-06-08 05:38
I now see that the uuid in your case is fff0, while in the case of @araines it is ff11. It is filtering in `ble_monitor/ble_parser/__init__.py` on this value 11 on line 64.

`                if adstruct[0] == 0x15 and adstruct[2] == 0x11:  # Thermoplus`

Try changing the last 0x11 to 0xF0

**Comment by Ernst79** [comment] 2021-06-08 09:57
Yes, you can. Can you try to add the 2nd line (`_LOGGER.error("DATA: %s", data.hex())` in `/custom_components/ble_monitor/ble_parser/__init__.py` (after line 61). This will generate an error for all messages that have FF in it. 

```python
            elif adstuct_type == 0xFF:  # AD type 'Manufacturer Specific Data'
                _LOGGER.error("DATA: %s", data.hex())
                if adstruct[0] == 0x1E and adstruct[2] == 0xFF and adstruct[3] == 0xFF:  # Kegtron
                    return parse_kegtron(self, adstruct, mac, rssi)
                if adstruct[0] == 0x15 and adstruct[2] == 0x11:  # Thermoplus
                    return parse_thermoplus(self, adstruct, mac, rssi)
            elif adstuct_type > 0x3D:
                # AD type not standard
```

Just post the log here, with the MAC, I can filter it for you.

**Comment by Ernst79** [comment] 2021-06-08 12:07
Thanks, I found the issue.

```
if adstruct[0] == 0x15 and adstruct[2] == 0x11: # Thermoplus
```

Same line as before, try changing the last 0x11 to 0x10

I have checked one mac, will check the others later, to see if this adstruct[2] value is variable, of fixed to either 10 or 11. If it is variable, we have to leave out the part from `and adstruct[2] == 0x11:`

**Comment by Ernst79** [comment] 2021-06-08 12:24
Check is finished, all your sensors show 0x10 in stead of 0x11. 

I'm in doubt of changing it to

```python
                if adstruct[0] == 0x15 and (adstruct[2] == 0x10 or adstruct[2] == 0x11):  # Thermoplus
                    return parse_thermoplus(self, adstruct, mac, rssi)
```

This will work for both of you. The other option will be to leave it out

```python
                if adstruct[0] == 0x15:  # Thermoplus
                    return parse_thermoplus(self, adstruct, mac, rssi)
```

This will help if Thermoplus decides to use other numbers as well. But this also has a bigger change of getting false data, as any manufacturer that is using `0xFF`, which have the same message length, will generate false sensors. The issue is that Thermoplus has chosen to use 0xFF, and not a proper UUID (for which they have to pay). Anyone can use this 0xFF, which is basically saying "manufacturer specific data".

I think for now, we stick to the first option. If people start complaining they can't find their thermoplus sensors, I know where to look for.

**Comment by Ernst79** [comment] 2021-06-08 12:43
Just thinking further, this 0x10 and 0x11 might be an indication of which device type it is. @araines @ACrazyConcept can you tell me which devices you both have? (smart hygrometer, lanyard hygrometer of mini hygrometer)?

**Comment by ACrazyConcept** [comment] 2021-06-08 13:02
Excellent! I will try in short while.
This is the types by MAC:
```
    - mac: '6F:15:00:00:0D:1F' # Mini hygrometer
    - mac: '70:F1:00:00:0C:D0' # Lanyard hygrometer
    - mac: '70:F1:00:00:0E:DC' # Lanyard hygrometer
    - mac: '70:F7:00:00:10:DC' # Lanyard hygrometer
    - mac: '70:F7:00:00:13:3F' # Lanyard hygrometer
    - mac: '70:F7:00:00:14:88' # Lanyard hygrometer
    - mac: '7B:41:00:00:04:54' # Mini hygrometer
```

**Comment by ACrazyConcept** [comment] 2021-06-08 13:09
@Ernst79 but can't you check the manufacturer? (I have no idea if it is consistent or unique)
`        Company: Mitel Semiconductor (16)`

**Comment by araines** [comment] 2021-06-08 13:20
@Ernst79 all mine are the Smart hydrometers

**Comment by Ernst79** [comment] 2021-06-08 13:28
You should turn report_unknown back to `False` (its only for testing, and getting logs for new devices). 

So, perhaps 
`0x10` = smart hydrometers
`0x11` = lanyard or mini meter


I have to check on the 0x16, where it is in the advertisements.

**Comment by Ernst79** [comment] 2021-06-08 13:41
You might be right, 

0x10 = 16 = Company: Mitel Semiconductor (16)
0x11 = 17 = Company: Widcomm, Inc (17)

Seems to be two different bluetooth chip manufacturers, but it is at least a good indication that these numbers are fixed. 
And it can also be used to identify devices into two groups

**Comment by Ernst79** [comment] 2021-06-08 14:47
3.1.1-beta has been released

**Comment by ACrazyConcept** [comment] 2021-06-08 15:08
I am getting this error:

```
2021-06-08 17:02:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ble_monitor/sensor.py", line 131, in async_run
sensors = await async_add_sensor(mac, sensortype, firmware)
File "/config/custom_components/ble_monitor/sensor.py", line 94, in async_add_sensor
device_sensors = MEASUREMENT_DICT[sensortype][0]
KeyError: 'Thermoplus'
```

**Comment by araines** [comment] 2021-06-08 15:13
Yup same issue for me:
```
2021-06-08 15:51:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ble_monitor/binary_sensor.py", line 119, in async_run
sensors = await async_add_binary_sensor(mac, sensortype, firmware)
File "/config/custom_components/ble_monitor/binary_sensor.py", line 82, in async_add_binary_sensor
device_sensors = MEASUREMENT_DICT[sensortype][1]
KeyError: 'Thermoplus'
2021-06-08 15:51:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/ble_monitor/sensor.py", line 131, in async_run
sensors = await async_add_sensor(mac, sensortype, firmware)
File "/config/custom_components/ble_monitor/sensor.py", line 94, in async_add_sensor
device_sensors = MEASUREMENT_DICT[sensortype][0]
KeyError: 'Thermoplus'
```

**Comment by Ernst79** [comment] 2021-06-08 15:41
ah, crap, that is because I changed the name of the devices. It's looking for the old device name, as that is what is stored in the HA registry. 

The easy way is delete the BLE monitor integration, restart and add it again. If you already have a lot of  other devices configured in the UI, there is another way. **Let me know if you need it, I will guide you through.**

Sorry for the inconvenience, but better make it right now.

**Comment by ACrazyConcept** [comment] 2021-06-08 15:54
Yup that did the trick. Thanks!

**Comment by araines** [comment] 2021-06-08 15:57
Same - all looking good to me now!  Thanks for everything :)

**Comment by Ernst79** [comment] 2021-06-10 06:22
3.1.1 has been released as final. Thanks for your help as well

**Closed by Ernst79** 2021-06-10 06:22 UTC
Labels: new sensor
