### ISSUE TITLE
[bug] Huge battery consumption, constant polling BLE 

### ISSUE THREAD

**Issue by vsimanin** [custom-components/ble_monitor#503] opened 2021-09-09 17:03 UTC
After the update on September 6th, the battery consumption of the devices went huge. I didn't notice it right away, but today the information from the sensors shocked me. The new Xiaomi watch was discharged by half in less than a week. During the analysis, we found out that the battery consumption is due to the constant polling of devices! The data is updated every 5-20 seconds (random time). I cannot influence this by changing any of the settings. Please help. There are more than 10 BLE devices in the house, the batteries are leaking.
None of the settings changed, there was only the addition of a new device, but this happened before September 6.

If you trust the version history, then the problem started with version 5.2.0 and higher.
Deivece: LYWSD02 (Xiaomi)

![Screenshot_20210909-193102](https://user-images.githubusercontent.com/9263449/132730453-e977c75a-1f49-4dba-a080-58ffca291d20.jpg) ![Screenshot_20210909-193116__01](https://user-images.githubusercontent.com/9263449/132730456-4319bc59-76fd-4d83-9073-08eb95d8f0bf.jpg) ![Screenshot_20210909-193125__01](https://user-images.githubusercontent.com/9263449/132730458-05c0b3b1-5e77-4a10-9a58-81590c567538.jpg)

![BLE](https://user-images.githubusercontent.com/9263449/132733288-720b9e85-2e9d-494a-b2a2-8c33144a4b91.PNG)

**Comment by Magalex2x14** [comment] 2021-09-09 17:56
@Ernst79 I contacted the @vsimanin on Telegram (thematic Russian-language group). Looks like a device or battery problem. I will update as there will be clarity...

**Comment by Ernst79** [comment] 2021-09-09 19:27
Ok, thanks. looks strange if it it is the integration that is causing this. Let me know the cause, I’m curious.

**Comment by Magalex2x14** [comment] 2021-09-10 15:51
The topic author was misled by frequent updates during the first period. I explained that the impact of ble_monitor integration on sensor energy consumption is physically impossible (except for the Active scan option). Readings in Home Assistant match MiHome app. In general, the problem is either with the sensor or with the battery (tends to sin on the battery). I close it.

**Closed by Magalex2x14** 2021-09-10 15:51 UTC
